/*----------------------------------------------------------------------------*/
/*                       Copyright (C) Tux64 2025, 2026                       */
/*                    https://github.com/bradleycha/tux64                     */
/*----------------------------------------------------------------------------*/
/* rescompiler/fontcompiler/src/tux64-fontcompiler/generator.c -              */
/*    Implementation for font map image data C source code generation.        */
/*----------------------------------------------------------------------------*/

#include "tux64-fontcompiler/tux64-fontcompiler.h"
#include "tux64-fontcompiler/generator.h"

#include <tux64/memory.h>

#include <stdlib.h>

#define TUX64_FONTCOMPILER_GENERATOR_CHARACTER_PIXELS_VERTICAL    8u
#define TUX64_FONTCOMPILER_GENERATOR_CHARACTER_PIXELS_HORIZONTAL  4u
#define TUX64_FONTCOMPILER_GENERATOR_CHARACTER_PIXELS \
   ( \
      TUX64_FONTCOMPILER_GENERATOR_CHARACTER_PIXELS_VERTICAL * \
      TUX64_FONTCOMPILER_GENERATOR_CHARACTER_PIXELS_HORIZONTAL \
   )
#define TUX64_FONTCOMPILER_GENERATOR_INPUT_RGB888_BYTES_PER_PIXEL 3u

#define TUX64_FONTCOMPILER_GENERATOR_CHARACTERS_VERTICAL    4u
#define TUX64_FONTCOMPILER_GENERATOR_CHARACTERS_HORIZONTAL  16u
#define TUX64_FONTCOMPILER_GENERATOR_CHARACTERS \
   ( \
      TUX64_FONTCOMPILER_GENERATOR_CHARACTERS_VERTICAL * \
      TUX64_FONTCOMPILER_GENERATOR_CHARACTERS_HORIZONTAL \
   )

#define TUX64_FONTCOMPILER_GENERATOR_INPUT_BYTES \
   ( \
      TUX64_FONTCOMPILER_GENERATOR_CHARACTER_PIXELS * \
      TUX64_FONTCOMPILER_GENERATOR_CHARACTERS * \
      TUX64_FONTCOMPILER_GENERATOR_INPUT_RGB888_BYTES_PER_PIXEL \
   )
#define TUX64_FONTCOMPILER_GENERATOR_OUTPUT_BYTES \
   (( \
      TUX64_FONTCOMPILER_GENERATOR_CHARACTER_PIXELS * \
      TUX64_FONTCOMPILER_GENERATOR_CHARACTERS \
   ) / 8u) /* storing as 1BPP */

#define TUX64_FONTCOMPILER_GENERATOR_OUTPUT_PRELUDE \
   "/* C source code generated by " TUX64_FONTCOMPILER_PACKAGE_NAME " version " TUX64_FONTCOMPILER_PACKAGE_VERSION " */\n" \
   "#define "
#define TUX64_FONTCOMPILER_GENERATOR_OUTPUT_DEFINE_SUFFIX \
   " \\\n"
#define TUX64_FONTCOMPILER_GENERATOR_OUTPUT_DEFINE_BYTE_PREFIX \
   "   TUX64_LITERAL_UINT8(0x"
#define TUX64_FONTCOMPILER_GENERATOR_OUTPUT_DEFINE_BYTE_SUFFIX_NEWLINE \
   "), \\\n"
#define TUX64_FONTCOMPILER_GENERATOR_OUTPUT_DEFINE_BYTE_SUFFIX_FINAL \
   ")\n"

#define TUX64_FONTCOMPILER_GENERATOR_OUTPUT_PRELUDE_CHARACTERS \
   TUX64_STRING_CHARACTERS(TUX64_FONTCOMPILER_GENERATOR_OUTPUT_PRELUDE)
#define TUX64_FONTCOMPILER_GENERATOR_OUTPUT_DEFINE_SUFFIX_CHARACTERS \
   TUX64_STRING_CHARACTERS(TUX64_FONTCOMPILER_GENERATOR_OUTPUT_DEFINE_SUFFIX)
#define TUX64_FONTCOMPILER_GENERATOR_OUTPUT_DEFINE_BYTE_PREFIX_CHARACTERS \
   TUX64_STRING_CHARACTERS(TUX64_FONTCOMPILER_GENERATOR_OUTPUT_DEFINE_BYTE_PREFIX)
#define TUX64_FONTCOMPILER_GENERATOR_OUTPUT_DEFINE_BYTE_SUFFIX_NEWLINE_CHARACTERS \
   TUX64_STRING_CHARACTERS(TUX64_FONTCOMPILER_GENERATOR_OUTPUT_DEFINE_BYTE_SUFFIX_NEWLINE)
#define TUX64_FONTCOMPILER_GENERATOR_OUTPUT_DEFINE_BYTE_SUFFIX_FINAL_CHARACTERS \
   TUX64_STRING_CHARACTERS(TUX64_FONTCOMPILER_GENERATOR_OUTPUT_DEFINE_BYTE_SUFFIX_FINAL)

static Tux64UInt32
tux64_fontcompiler_generator_calculate_output_length(
   Tux64UInt32 identifier_characters
) {
   Tux64UInt32 characters;

   characters = TUX64_LITERAL_UINT32(0u);

   /* prefix strings */
   characters = characters +
      TUX64_LITERAL_UINT32(TUX64_FONTCOMPILER_GENERATOR_OUTPUT_PRELUDE_CHARACTERS) +
      identifier_characters +
      TUX64_LITERAL_UINT32(TUX64_FONTCOMPILER_GENERATOR_OUTPUT_DEFINE_SUFFIX_CHARACTERS);

   /* all comma-terminated byte entries */
   characters = characters +
      (
         TUX64_LITERAL_UINT32(TUX64_FONTCOMPILER_GENERATOR_OUTPUT_DEFINE_BYTE_PREFIX_CHARACTERS) +
         TUX64_LITERAL_UINT32(2u) +
         TUX64_LITERAL_UINT32(TUX64_FONTCOMPILER_GENERATOR_OUTPUT_DEFINE_BYTE_SUFFIX_NEWLINE_CHARACTERS)
      ) * TUX64_LITERAL_UINT32(TUX64_FONTCOMPILER_GENERATOR_OUTPUT_BYTES - 1u);

   /* final byte entry and macro termination */
   characters = characters +
      TUX64_LITERAL_UINT32(TUX64_FONTCOMPILER_GENERATOR_OUTPUT_DEFINE_BYTE_PREFIX_CHARACTERS) +
      TUX64_LITERAL_UINT32(2u) +
      TUX64_LITERAL_UINT32(TUX64_FONTCOMPILER_GENERATOR_OUTPUT_DEFINE_BYTE_SUFFIX_FINAL_CHARACTERS);

   return (characters * TUX64_LITERAL_UINT32(sizeof(char)));
}

static Tux64UInt16
tux64_fontcompiler_generator_get_pixel_index(
   Tux64UInt8 idx_character,
   Tux64UInt8 idx_row,
   Tux64UInt8 idx_column
) {
   Tux64UInt8 idx_character_h;
   Tux64UInt8 idx_character_v;
   Tux64UInt16 idx;

   /* try not to think about this too hard.  just trust that this code works. */

   idx_character_h = idx_character % TUX64_LITERAL_UINT8(TUX64_FONTCOMPILER_GENERATOR_CHARACTERS_HORIZONTAL);
   idx_character_v = idx_character / TUX64_LITERAL_UINT8(TUX64_FONTCOMPILER_GENERATOR_CHARACTERS_HORIZONTAL);

   idx = TUX64_LITERAL_UINT16(0u);

   idx = idx + (idx_character_h * TUX64_LITERAL_UINT16(TUX64_FONTCOMPILER_GENERATOR_CHARACTER_PIXELS_HORIZONTAL));
   idx = idx + (idx_character_v * TUX64_LITERAL_UINT16(TUX64_FONTCOMPILER_GENERATOR_CHARACTER_PIXELS * TUX64_FONTCOMPILER_GENERATOR_CHARACTERS_HORIZONTAL));
   idx = idx + (idx_row * TUX64_LITERAL_UINT16(TUX64_FONTCOMPILER_GENERATOR_CHARACTER_PIXELS_HORIZONTAL * TUX64_FONTCOMPILER_GENERATOR_CHARACTERS_HORIZONTAL));
   idx = idx + (idx_column);

   return idx;
}

static Tux64UInt8
tux64_fontcompiler_generator_encode_pixel(
   const Tux64UInt8 * input_data,
   Tux64UInt8 idx_character,
   Tux64UInt8 idx_row,
   Tux64UInt8 idx_column
) {
   Tux64UInt16 idx_pixel;
   const Tux64UInt8 * iter_pixels;
   Tux64UInt16 intensity;
   Tux64UInt8 i;

   idx_pixel = tux64_fontcompiler_generator_get_pixel_index(
      idx_character,
      idx_row,
      idx_column
   );

   iter_pixels = &input_data[idx_pixel * TUX64_LITERAL_UINT16(TUX64_FONTCOMPILER_GENERATOR_INPUT_RGB888_BYTES_PER_PIXEL)];

   /* take the average of the RGB channels */
   intensity = TUX64_LITERAL_UINT16(0u);
   i = TUX64_LITERAL_UINT8(TUX64_FONTCOMPILER_GENERATOR_INPUT_RGB888_BYTES_PER_PIXEL - 1u);
   do {
      intensity += (Tux64UInt16)(*iter_pixels);

      iter_pixels++;
      i--;
   } while (i != TUX64_LITERAL_UINT8(0u));
   intensity /= TUX64_LITERAL_UINT16(TUX64_FONTCOMPILER_GENERATOR_INPUT_RGB888_BYTES_PER_PIXEL);

   /* quantize to 1-bit intensity */
   if (intensity < TUX64_LITERAL_UINT16(TUX64_UINT8_MAX / 2u)) {
      return TUX64_LITERAL_UINT8(0u);
   }

   return TUX64_LITERAL_UINT8(1u);
}

static Tux64UInt8
tux64_fontcompiler_generator_encode_row(
   const Tux64UInt8 * input_data,
   Tux64UInt8 idx_character,
   Tux64UInt8 idx_row
) {
   Tux64UInt8 nibble;
   Tux64UInt8 idx_column;

   nibble = TUX64_LITERAL_UINT8(0u);

   idx_column = TUX64_LITERAL_UINT8(0u);
   do {
      nibble = nibble << TUX64_LITERAL_UINT8(1u);
      nibble = nibble | tux64_fontcompiler_generator_encode_pixel(
         input_data,
         idx_character,
         idx_row,
         idx_column
      );

      idx_column++;
   } while (idx_column != TUX64_LITERAL_UINT8(TUX64_FONTCOMPILER_GENERATOR_CHARACTER_PIXELS_HORIZONTAL));

   return nibble;
}

static Tux64UInt8
tux64_fontcompiler_generator_format_character_row(
   const Tux64UInt8 * input_data,
   Tux64UInt8 idx_character,
   Tux64UInt8 idx_row
) {
   Tux64UInt8 nibble;

   nibble = tux64_fontcompiler_generator_encode_row(
      input_data,
      idx_character,
      idx_row
   );

   if (nibble >= TUX64_LITERAL_UINT8(0xau)) {
      return ('a' + nibble - TUX64_LITERAL_UINT8(0xau));
   }

   return ('0' + nibble);
}

static Tux64UInt8 *
tux64_fontcompiler_generator_format_character_byte(
   const Tux64UInt8 * input_data,
   Tux64UInt8 * output_data,
   Tux64UInt8 idx_character,
   Tux64UInt8 idx_rows
) {
   *output_data++ = tux64_fontcompiler_generator_format_character_row(
      input_data,
      idx_character,
      idx_rows + TUX64_LITERAL_UINT8(0u)
   );
   *output_data++ = tux64_fontcompiler_generator_format_character_row(
      input_data,
      idx_character,
      idx_rows + TUX64_LITERAL_UINT8(1u)
   );

   return output_data;
}

static Tux64UInt8 *
tux64_fontcompiler_generator_format_line_define(
   const Tux64UInt8 * input_data,
   Tux64UInt8 * output_data,
   Tux64UInt8 idx_character,
   Tux64UInt8 idx_rows,
   const char * fmt_suffix_ptr,
   Tux64UInt32 fmt_suffix_characters
) {
   tux64_memory_copy(
      output_data,
      TUX64_FONTCOMPILER_GENERATOR_OUTPUT_DEFINE_BYTE_PREFIX,
      TUX64_LITERAL_UINT32(TUX64_FONTCOMPILER_GENERATOR_OUTPUT_DEFINE_BYTE_PREFIX_CHARACTERS)
   );
   output_data += TUX64_FONTCOMPILER_GENERATOR_OUTPUT_DEFINE_BYTE_PREFIX_CHARACTERS;

   output_data = tux64_fontcompiler_generator_format_character_byte(
      input_data,
      output_data,
      idx_character,
      idx_rows
   );

   tux64_memory_copy(
      output_data,
      fmt_suffix_ptr,
      fmt_suffix_characters
   );
   output_data += fmt_suffix_characters;

   return output_data;
}

static Tux64UInt8 *
tux64_fontcompiler_generator_format_line_define_nonterminating(
   const Tux64UInt8 * input_data,
   Tux64UInt8 * output_data,
   Tux64UInt8 idx_character,
   Tux64UInt8 count_rows 
) {
   Tux64UInt8 idx_row;

   idx_row = TUX64_LITERAL_UINT8(0u);
   do {
      output_data = tux64_fontcompiler_generator_format_line_define(
         input_data,
         output_data,
         idx_character,
         idx_row,
         TUX64_FONTCOMPILER_GENERATOR_OUTPUT_DEFINE_BYTE_SUFFIX_NEWLINE,
         TUX64_LITERAL_UINT32(TUX64_FONTCOMPILER_GENERATOR_OUTPUT_DEFINE_BYTE_SUFFIX_NEWLINE_CHARACTERS)
      );

      /* each byte consists of 2 rows */
      idx_row += TUX64_LITERAL_UINT8(2u);
   } while (idx_row != count_rows);
   
   return output_data;
}

static void
tux64_fontcompiler_generator_format(
   const Tux64UInt8 * data,
   const struct Tux64String * identifier,
   Tux64UInt8 * output_data
) {
   Tux64UInt8 * iter_output_data;
   Tux64UInt8 idx_character;

   iter_output_data = output_data;

   /* format the prelude before the identifier */
   tux64_memory_copy(
      iter_output_data,
      TUX64_FONTCOMPILER_GENERATOR_OUTPUT_PRELUDE,
      TUX64_LITERAL_UINT32(TUX64_FONTCOMPILER_GENERATOR_OUTPUT_PRELUDE_CHARACTERS * sizeof(char))
   );
   iter_output_data += (TUX64_FONTCOMPILER_GENERATOR_OUTPUT_PRELUDE_CHARACTERS * sizeof(char));

   /* format the identifier itself */
   tux64_memory_copy(
      iter_output_data,
      identifier->ptr,
      identifier->characters * TUX64_LITERAL_UINT32(sizeof(char))
   );
   iter_output_data += (identifier->characters * sizeof(char));

   /* format the #define characters after the identifier */
   tux64_memory_copy(
      iter_output_data,
      TUX64_FONTCOMPILER_GENERATOR_OUTPUT_DEFINE_SUFFIX,
      TUX64_LITERAL_UINT32(TUX64_FONTCOMPILER_GENERATOR_OUTPUT_DEFINE_SUFFIX_CHARACTERS * sizeof(char))
   );
   iter_output_data += (TUX64_FONTCOMPILER_GENERATOR_OUTPUT_DEFINE_SUFFIX_CHARACTERS * sizeof(char));

   /* iterate through all but the last characters.  the last one is a special */
   /* case where the last output byte is formatted differently */
   idx_character = TUX64_LITERAL_UINT8(0u);
   do {
      iter_output_data = tux64_fontcompiler_generator_format_line_define_nonterminating(
         data,
         iter_output_data,
         idx_character,
         TUX64_LITERAL_UINT8(TUX64_FONTCOMPILER_GENERATOR_CHARACTER_PIXELS_VERTICAL)
      );

      idx_character++;
   } while (idx_character != TUX64_LITERAL_UINT8(TUX64_FONTCOMPILER_GENERATOR_CHARACTERS - 1u));

   /* now iterate through all rows in the last character until the last 2 */
   iter_output_data = tux64_fontcompiler_generator_format_line_define_nonterminating(
      data,
      iter_output_data,
      TUX64_LITERAL_UINT8(TUX64_FONTCOMPILER_GENERATOR_CHARACTERS - 1u),
      TUX64_LITERAL_UINT8(TUX64_FONTCOMPILER_GENERATOR_CHARACTER_PIXELS_VERTICAL - 2u)
   );

   /* finally, format the last lines */
   (void)tux64_fontcompiler_generator_format_line_define(
      data,
      iter_output_data,
      TUX64_LITERAL_UINT8(TUX64_FONTCOMPILER_GENERATOR_CHARACTERS - 1u),
      TUX64_LITERAL_UINT8(TUX64_FONTCOMPILER_GENERATOR_CHARACTER_PIXELS_VERTICAL - 2u),
      TUX64_FONTCOMPILER_GENERATOR_OUTPUT_DEFINE_BYTE_SUFFIX_FINAL,
      TUX64_LITERAL_UINT32(TUX64_FONTCOMPILER_GENERATOR_OUTPUT_DEFINE_BYTE_SUFFIX_FINAL_CHARACTERS)
   );

   return;
}

struct Tux64FontCompilerGeneratorParseResult
tux64_fontcompiler_generator_parse(
   const Tux64UInt8 * data,
   Tux64UInt32 bytes,
   const struct Tux64String * identifier
) {
   struct Tux64FontCompilerGeneratorParseResult result;  
   Tux64UInt8 * output_data;
   Tux64UInt32 output_bytes;

   if (bytes != TUX64_LITERAL_UINT32(TUX64_FONTCOMPILER_GENERATOR_INPUT_BYTES)) {
      result.status = TUX64_FONTCOMPILER_GENERATOR_PARSE_STATUS_INVALID_IMAGE_FORMAT;
      return result;
   }

   output_bytes = tux64_fontcompiler_generator_calculate_output_length(
      identifier->characters
   );

   output_data = (Tux64UInt8 *)malloc(output_bytes);
   if (output_data == NULL) {
      result.status = TUX64_FONTCOMPILER_GENERATOR_PARSE_STATUS_OUT_OF_MEMORY;
      return result;
   }
   
   tux64_fontcompiler_generator_format(
      data,
      identifier,
      output_data
   );

   result.status = TUX64_FONTCOMPILER_GENERATOR_PARSE_STATUS_OK;
   result.payload.ok.data = output_data;
   result.payload.ok.bytes = output_bytes;
   return result;
}

