/*----------------------------------------------------------------------------*/
/*                          Copyright (C) Tux64 2025                          */
/*                    https://github.com/bradleycha/tux64                     */
/*----------------------------------------------------------------------------*/
/* boot/src/tux64-boot/stage1/fbcon.c - Implementations for framebuffer       */
/*    console.                                                                */
/*----------------------------------------------------------------------------*/

#include "tux64-boot/tux64-boot.h"
#include "tux64-boot/stage1/fbcon.h"

#include "tux64-boot/stage1/video.h"

/* generated by tux64-fontcompiler, provides TUX64_BOOT_STAGE1_FONTMAP_BIN */
#include "src/tux64-boot/stage1/fontmap.bin.c"

static const Tux64UInt8
tux64_boot_stage1_fbcon_fontmap_compressed [] = {
   TUX64_BOOT_STAGE1_FONTMAP_BIN
};

void
tux64_boot_stage1_fbcon_initialize(
   Tux64BootStage1VideoPixel color_foreground,
   Tux64BootStage1VideoPixel color_background
) {
   /* TODO: decompress the font into an RSP DMA buffer, coloring the pixels */
   /* and making them ready to be directly copied into the framebuffer. */
   (void)color_foreground;
   (void)color_background;
   (void)tux64_boot_stage1_fbcon_fontmap_compressed;
   return;
}

void
tux64_boot_stage1_fbcon_render(void) {
   /* TODO: implement */
   return;
}

