/*----------------------------------------------------------------------------*/
/*                          Copyright (C) Tux64 2026                          */
/*                    https://github.com/bradleycha/tux64                     */
/*----------------------------------------------------------------------------*/
/* boot/src/tux64-boot/stage1/strings.c - Glue code for fbcon text strings.   */
/*----------------------------------------------------------------------------*/

#include "tux64-boot/tux64-boot.h"
#include "tux64-boot/stage1/strings.h"

#include "tux64-boot/stage1/fbcon.h"

/* generated by tux64-textcompiler, provides all string data */
#include "src/tux64-boot/stage1/strings.bin.c"

static const Tux64BootStage1FbconLabelCharacter
tux64_boot_stage1_strings_data_splash [] = {
   TUX64_BOOT_STAGE1_STRINGS_SPLASH_DATA
};

static const Tux64BootStage1FbconLabelCharacter
tux64_boot_stage1_strings_data_hello_world [] = {
   TUX64_BOOT_STAGE1_STRINGS_HELLO_WORLD_DATA
};

/* all text strings stored next to each other in memory to hopefully improve */
/* caching via locality */
static const struct Tux64BootStage1FbconText
tux64_boot_stage1_strings [] = {
   {
      .ptr        = tux64_boot_stage1_strings_data_splash,
      .length     = TUX64_LITERAL_UINT8(TUX64_BOOT_STAGE1_STRINGS_SPLASH_LENGTH),
      .capacity   = TUX64_LITERAL_UINT8(TUX64_BOOT_STAGE1_STRINGS_SPLASH_LENGTH)
   },
   {
      .ptr        = tux64_boot_stage1_strings_data_hello_world,
      .length     = TUX64_LITERAL_UINT8(TUX64_BOOT_STAGE1_STRINGS_HELLO_WORLD_LENGTH),
      .capacity   = TUX64_LITERAL_UINT8(TUX64_BOOT_STAGE1_STRINGS_HELLO_WORLD_LENGTH)
   }
};

const struct Tux64BootStage1FbconText *
tux64_boot_stage1_strings_splash = &tux64_boot_stage1_strings[0u];
const struct Tux64BootStage1FbconText *
tux64_boot_stage1_strings_hello_world = &tux64_boot_stage1_strings[1u];

