/*----------------------------------------------------------------------------*/
/*                          Copyright (C) Tux64 2026                          */
/*                    https://github.com/bradleycha/tux64                     */
/*----------------------------------------------------------------------------*/
/* boot/src/tux64-boot/stage1/strings.c - Glue code for fbcon text strings.   */
/*----------------------------------------------------------------------------*/

#include "tux64-boot/tux64-boot.h"
#include "tux64-boot/stage1/strings.h"

#include "tux64-boot/stage1/fbcon.h"
#include "tux64-boot/stage1/format.h"

/* generated by tux64-textcompiler, provides all string data */
#include "src/tux64-boot/stage1/strings.bin.c"

/* alignment manually set to '1' to remove unnecessary padding added for each */
/* individual slab of data. */
#define TUX64_BOOT_STAGE1_STRINGS_DATA_DEFINE(identifier, data) \
   __attribute__((aligned(1))) \
   static const Tux64BootStage1FbconLabelCharacter \
   identifier [] = { \
      data \
   }

TUX64_BOOT_STAGE1_STRINGS_DATA_DEFINE(
   tux64_boot_stage1_strings_format_mib_static_data,
   TUX64_BOOT_STAGE1_STRINGS_FORMAT_MIB_STATIC_DATA
);
TUX64_BOOT_STAGE1_STRINGS_DATA_DEFINE(
   tux64_boot_stage1_strings_format_percentage_static_data,
   TUX64_BOOT_STAGE1_STRINGS_FORMAT_PERCENTAGE_STATIC_DATA
);
TUX64_BOOT_STAGE1_STRINGS_DATA_DEFINE(
   tux64_boot_stage1_strings_format_error_data,
   TUX64_BOOT_STAGE1_STRINGS_FORMAT_ERROR_DATA
);
TUX64_BOOT_STAGE1_STRINGS_DATA_DEFINE(
   tux64_boot_stage1_strings_format_loading_data,
   TUX64_BOOT_STAGE1_STRINGS_FORMAT_LOADING_DATA
);
TUX64_BOOT_STAGE1_STRINGS_DATA_DEFINE(
   tux64_boot_stage1_strings_splash_data,
   TUX64_BOOT_STAGE1_STRINGS_SPLASH_DATA
);
TUX64_BOOT_STAGE1_STRINGS_DATA_DEFINE(
   tux64_boot_stage1_strings_memory_total_data,
   TUX64_BOOT_STAGE1_STRINGS_MEMORY_TOTAL_DATA
);
TUX64_BOOT_STAGE1_STRINGS_DATA_DEFINE(
   tux64_boot_stage1_strings_memory_free_data,
   TUX64_BOOT_STAGE1_STRINGS_MEMORY_FREE_DATA
);
TUX64_BOOT_STAGE1_STRINGS_DATA_DEFINE(
   tux64_boot_stage1_strings_kernel_image_data,
   TUX64_BOOT_STAGE1_STRINGS_KERNEL_IMAGE_DATA
);
TUX64_BOOT_STAGE1_STRINGS_DATA_DEFINE(
   tux64_boot_stage1_strings_kernel_memory_data,
   TUX64_BOOT_STAGE1_STRINGS_KERNEL_MEMORY_DATA
);
TUX64_BOOT_STAGE1_STRINGS_DATA_DEFINE(
   tux64_boot_stage1_strings_initramfs_image_data,
   TUX64_BOOT_STAGE1_STRINGS_INITRAMFS_IMAGE_DATA
);
TUX64_BOOT_STAGE1_STRINGS_DATA_DEFINE(
   tux64_boot_stage1_strings_kernel_address_load_data,
   TUX64_BOOT_STAGE1_STRINGS_KERNEL_ADDRESS_LOAD_DATA
);
TUX64_BOOT_STAGE1_STRINGS_DATA_DEFINE(
   tux64_boot_stage1_strings_kernel_address_entry_data,
   TUX64_BOOT_STAGE1_STRINGS_KERNEL_ADDRESS_ENTRY_DATA
);
TUX64_BOOT_STAGE1_STRINGS_DATA_DEFINE(
   tux64_boot_stage1_strings_no_checksum_data,
   TUX64_BOOT_STAGE1_STRINGS_NO_CHECKSUM_DATA
);
TUX64_BOOT_STAGE1_STRINGS_DATA_DEFINE(
   tux64_boot_stage1_strings_file_bootloader_stage2_data,
   TUX64_BOOT_STAGE1_STRINGS_FILE_BOOTLOADER_STAGE2_DATA
);
TUX64_BOOT_STAGE1_STRINGS_DATA_DEFINE(
   tux64_boot_stage1_strings_file_kernel_data,
   TUX64_BOOT_STAGE1_STRINGS_FILE_KERNEL_DATA
);
TUX64_BOOT_STAGE1_STRINGS_DATA_DEFINE(
   tux64_boot_stage1_strings_file_initramfs_data,
   TUX64_BOOT_STAGE1_STRINGS_FILE_INITRAMFS_DATA
);
TUX64_BOOT_STAGE1_STRINGS_DATA_DEFINE(
   tux64_boot_stage1_strings_file_command_line_data,
   TUX64_BOOT_STAGE1_STRINGS_FILE_COMMAND_LINE_DATA
);
TUX64_BOOT_STAGE1_STRINGS_DATA_DEFINE(
   tux64_boot_stage1_strings_error_no_memory_data,
   TUX64_BOOT_STAGE1_STRINGS_ERROR_NO_MEMORY_DATA
);
TUX64_BOOT_STAGE1_STRINGS_DATA_DEFINE(
   tux64_boot_stage1_strings_error_io_data,
   TUX64_BOOT_STAGE1_STRINGS_ERROR_IO_DATA
);
TUX64_BOOT_STAGE1_STRINGS_DATA_DEFINE(
   tux64_boot_stage1_strings_error_checksum_data,
   TUX64_BOOT_STAGE1_STRINGS_ERROR_CHECKSUM_DATA
);
TUX64_BOOT_STAGE1_STRINGS_DATA_DEFINE(
   tux64_boot_stage1_strings_hello_world_data,
   TUX64_BOOT_STAGE1_STRINGS_HELLO_WORLD_DATA
);
TUX64_BOOT_STAGE1_STRINGS_DATA_DEFINE(
   tux64_boot_stage1_strings_error_test_data,
   TUX64_BOOT_STAGE1_STRINGS_ERROR_TEST_DATA
);

/* alignment manually set for same reason as above.  this time the size of a */
/* pointer since one of our fields is a pointer, with the rest of the fields */
/* being 32-bit, thus our minimum required alignment has to be either 32-bit */
/* or 64-bit, depending on the ABI. */
#define TUX64_BOOT_STAGE1_STRINGS_TEXT_DEFINE(identifier, identifier_ptr, identifier_length) \
   __attribute__((aligned(sizeof(Tux64UIntPtr)))) \
   const struct Tux64BootStage1FbconText \
   identifier = { \
      .ptr        = identifier_ptr , \
      .length  = TUX64_LITERAL_UINT8( identifier_length ), \
   }
#define TUX64_BOOT_STAGE1_STRINGS_TEXT_LABEL_DEFINE(identifier, identifier_ptr, identifier_length, identifier_capacity) \
   __attribute__((aligned(sizeof(Tux64UIntPtr)))) \
   const struct Tux64BootStage1FbconTextLabel \
   identifier = { \
      .text = { \
         .ptr        = identifier_ptr , \
         .length  = TUX64_LITERAL_UINT8( identifier_length ), \
      }, \
      .capacity   = TUX64_LITERAL_UINT8( identifier_capacity ) \
   }

/* defining these separately instead of in an array allows dead code */
/* elimination to work better.  also, the compiler tends to place these */
/* close to each other, so we still get good data locality.  if caching */
/* becomes a problem, we can just manually place them in a separate section. */
TUX64_BOOT_STAGE1_STRINGS_TEXT_DEFINE(
   tux64_boot_stage1_strings_format_mib_static,
   tux64_boot_stage1_strings_format_mib_static_data,
   TUX64_BOOT_STAGE1_STRINGS_FORMAT_MIB_STATIC_LENGTH
);
TUX64_BOOT_STAGE1_STRINGS_TEXT_DEFINE(
   tux64_boot_stage1_strings_format_percentage_static,
   tux64_boot_stage1_strings_format_percentage_static_data,
   TUX64_BOOT_STAGE1_STRINGS_FORMAT_PERCENTAGE_STATIC_LENGTH
);
TUX64_BOOT_STAGE1_STRINGS_TEXT_DEFINE(
   tux64_boot_stage1_strings_format_error,
   tux64_boot_stage1_strings_format_error_data,
   TUX64_BOOT_STAGE1_STRINGS_FORMAT_ERROR_LENGTH
);
TUX64_BOOT_STAGE1_STRINGS_TEXT_DEFINE(
   tux64_boot_stage1_strings_format_loading,
   tux64_boot_stage1_strings_format_loading_data,
   TUX64_BOOT_STAGE1_STRINGS_FORMAT_LOADING_LENGTH
);
TUX64_BOOT_STAGE1_STRINGS_TEXT_LABEL_DEFINE(
   tux64_boot_stage1_strings_splash,
   tux64_boot_stage1_strings_splash_data,
   TUX64_BOOT_STAGE1_STRINGS_SPLASH_LENGTH,
   TUX64_BOOT_STAGE1_STRINGS_SPLASH_LENGTH
);
TUX64_BOOT_STAGE1_STRINGS_TEXT_LABEL_DEFINE(
   tux64_boot_stage1_strings_memory_total,
   tux64_boot_stage1_strings_memory_total_data,
   TUX64_BOOT_STAGE1_STRINGS_MEMORY_TOTAL_LENGTH,
   TUX64_BOOT_STAGE1_STRINGS_MEMORY_TOTAL_LENGTH + TUX64_BOOT_STAGE1_FORMAT_BUFFER_CHARACTERS_MIB
);
TUX64_BOOT_STAGE1_STRINGS_TEXT_LABEL_DEFINE(
   tux64_boot_stage1_strings_memory_free,
   tux64_boot_stage1_strings_memory_free_data,
   TUX64_BOOT_STAGE1_STRINGS_MEMORY_FREE_LENGTH,
   TUX64_BOOT_STAGE1_STRINGS_MEMORY_FREE_LENGTH + TUX64_BOOT_STAGE1_FORMAT_BUFFER_CHARACTERS_MIB
);
TUX64_BOOT_STAGE1_STRINGS_TEXT_LABEL_DEFINE(
   tux64_boot_stage1_strings_kernel_image,
   tux64_boot_stage1_strings_kernel_image_data,
   TUX64_BOOT_STAGE1_STRINGS_KERNEL_IMAGE_LENGTH,
   TUX64_BOOT_STAGE1_STRINGS_KERNEL_IMAGE_LENGTH + TUX64_BOOT_STAGE1_FORMAT_BUFFER_CHARACTERS_MIB
);
TUX64_BOOT_STAGE1_STRINGS_TEXT_LABEL_DEFINE(
   tux64_boot_stage1_strings_kernel_memory,
   tux64_boot_stage1_strings_kernel_memory_data,
   TUX64_BOOT_STAGE1_STRINGS_KERNEL_MEMORY_LENGTH,
   TUX64_BOOT_STAGE1_STRINGS_KERNEL_MEMORY_LENGTH + TUX64_BOOT_STAGE1_FORMAT_BUFFER_CHARACTERS_MIB
);
TUX64_BOOT_STAGE1_STRINGS_TEXT_LABEL_DEFINE(
   tux64_boot_stage1_strings_initramfs_image,
   tux64_boot_stage1_strings_initramfs_image_data,
   TUX64_BOOT_STAGE1_STRINGS_INITRAMFS_IMAGE_LENGTH,
   TUX64_BOOT_STAGE1_STRINGS_INITRAMFS_IMAGE_LENGTH + TUX64_BOOT_STAGE1_FORMAT_BUFFER_CHARACTERS_MIB
);
TUX64_BOOT_STAGE1_STRINGS_TEXT_LABEL_DEFINE(
   tux64_boot_stage1_strings_kernel_address_load,
   tux64_boot_stage1_strings_kernel_address_load_data,
   TUX64_BOOT_STAGE1_STRINGS_KERNEL_ADDRESS_LOAD_LENGTH,
   TUX64_BOOT_STAGE1_STRINGS_KERNEL_ADDRESS_LOAD_LENGTH + TUX64_BOOT_STAGE1_FORMAT_BUFFER_CHARACTERS_ADDRESS
);
TUX64_BOOT_STAGE1_STRINGS_TEXT_LABEL_DEFINE(
   tux64_boot_stage1_strings_kernel_address_entry,
   tux64_boot_stage1_strings_kernel_address_entry_data,
   TUX64_BOOT_STAGE1_STRINGS_KERNEL_ADDRESS_ENTRY_LENGTH,
   TUX64_BOOT_STAGE1_STRINGS_KERNEL_ADDRESS_ENTRY_LENGTH + TUX64_BOOT_STAGE1_FORMAT_BUFFER_CHARACTERS_ADDRESS
);
TUX64_BOOT_STAGE1_STRINGS_TEXT_LABEL_DEFINE(
   tux64_boot_stage1_strings_no_checksum,
   tux64_boot_stage1_strings_no_checksum_data,
   TUX64_BOOT_STAGE1_STRINGS_NO_CHECKSUM_LENGTH,
   TUX64_BOOT_STAGE1_STRINGS_NO_CHECKSUM_LENGTH
);
TUX64_BOOT_STAGE1_STRINGS_TEXT_DEFINE(
   tux64_boot_stage1_strings_file_bootloader_stage2,
   tux64_boot_stage1_strings_file_bootloader_stage2_data,
   TUX64_BOOT_STAGE1_STRINGS_FILE_BOOTLOADER_STAGE2_LENGTH
);
TUX64_BOOT_STAGE1_STRINGS_TEXT_DEFINE(
   tux64_boot_stage1_strings_file_kernel,
   tux64_boot_stage1_strings_file_kernel_data,
   TUX64_BOOT_STAGE1_STRINGS_FILE_KERNEL_LENGTH
);
TUX64_BOOT_STAGE1_STRINGS_TEXT_DEFINE(
   tux64_boot_stage1_strings_file_initramfs,
   tux64_boot_stage1_strings_file_initramfs_data,
   TUX64_BOOT_STAGE1_STRINGS_FILE_INITRAMFS_LENGTH
);
TUX64_BOOT_STAGE1_STRINGS_TEXT_DEFINE(
   tux64_boot_stage1_strings_file_command_line,
   tux64_boot_stage1_strings_file_command_line_data,
   TUX64_BOOT_STAGE1_STRINGS_FILE_COMMAND_LINE_LENGTH
);
TUX64_BOOT_STAGE1_STRINGS_TEXT_DEFINE(
   tux64_boot_stage1_strings_error_no_memory,
   tux64_boot_stage1_strings_error_no_memory_data,
   TUX64_BOOT_STAGE1_STRINGS_ERROR_NO_MEMORY_LENGTH
);
TUX64_BOOT_STAGE1_STRINGS_TEXT_DEFINE(
   tux64_boot_stage1_strings_error_io,
   tux64_boot_stage1_strings_error_io_data,
   TUX64_BOOT_STAGE1_STRINGS_ERROR_IO_LENGTH
);
TUX64_BOOT_STAGE1_STRINGS_TEXT_DEFINE(
   tux64_boot_stage1_strings_error_checksum,
   tux64_boot_stage1_strings_error_checksum_data,
   TUX64_BOOT_STAGE1_STRINGS_ERROR_CHECKSUM_LENGTH
);
TUX64_BOOT_STAGE1_STRINGS_TEXT_LABEL_DEFINE(
   tux64_boot_stage1_strings_hello_world,
   tux64_boot_stage1_strings_hello_world_data,
   TUX64_BOOT_STAGE1_STRINGS_HELLO_WORLD_LENGTH,
   TUX64_BOOT_STAGE1_STRINGS_HELLO_WORLD_LENGTH + TUX64_BOOT_STAGE1_FORMAT_BUFFER_CHARACTERS_PERCENTAGE
);
TUX64_BOOT_STAGE1_STRINGS_TEXT_DEFINE(
   tux64_boot_stage1_strings_error_test,
   tux64_boot_stage1_strings_error_test_data,
   TUX64_BOOT_STAGE1_STRINGS_ERROR_TEST_LENGTH
);

