/*----------------------------------------------------------------------------*/
/*                          Copyright (C) Tux64 2026                          */
/*                    https://github.com/bradleycha/tux64                     */
/*----------------------------------------------------------------------------*/
/* boot/src/tux64-boot/stage1/strings.c - Glue code for fbcon text strings.   */
/*----------------------------------------------------------------------------*/

#include "tux64-boot/tux64-boot.h"
#include "tux64-boot/stage1/strings.h"

#include "tux64-boot/stage1/fbcon.h"
#include "tux64-boot/stage1/format.h"

/* generated by tux64-textcompiler, provides all string data */
#include "src/tux64-boot/stage1/strings.bin.c"

/* alignment manually set to '1' to remove unnecessary padding added for each */
/* individual slab of data. */
#define TUX64_BOOT_STAGE1_STRINGS_DATA_DEFINE(identifier, data) \
   __attribute__((aligned(1))) \
   static const Tux64BootStage1FbconLabelCharacter \
   identifier [] = { \
      data \
   }

TUX64_BOOT_STAGE1_STRINGS_DATA_DEFINE(
   tux64_boot_stage1_strings_splash_data,
   TUX64_BOOT_STAGE1_STRINGS_SPLASH_DATA
);
TUX64_BOOT_STAGE1_STRINGS_DATA_DEFINE(
   tux64_boot_stage1_strings_memory_total_data,
   TUX64_BOOT_STAGE1_STRINGS_MEMORY_TOTAL_DATA
);
TUX64_BOOT_STAGE1_STRINGS_DATA_DEFINE(
   tux64_boot_stage1_strings_memory_free_data,
   TUX64_BOOT_STAGE1_STRINGS_MEMORY_FREE_DATA
);
TUX64_BOOT_STAGE1_STRINGS_DATA_DEFINE(
   tux64_boot_stage1_strings_kernel_image_data,
   TUX64_BOOT_STAGE1_STRINGS_KERNEL_IMAGE_DATA
);
TUX64_BOOT_STAGE1_STRINGS_DATA_DEFINE(
   tux64_boot_stage1_strings_initramfs_image_data,
   TUX64_BOOT_STAGE1_STRINGS_INITRAMFS_IMAGE_DATA
);
TUX64_BOOT_STAGE1_STRINGS_DATA_DEFINE(
   tux64_boot_stage1_strings_no_checksum_data,
   TUX64_BOOT_STAGE1_STRINGS_NO_CHECKSUM_DATA
);
TUX64_BOOT_STAGE1_STRINGS_DATA_DEFINE(
   tux64_boot_stage1_strings_hello_world_data,
   TUX64_BOOT_STAGE1_STRINGS_HELLO_WORLD_DATA
);

#define TUX64_BOOT_STAGE1_STRINGS_TEXT_DEFINE(identifier, identifier_ptr, identifier_length, identifier_capacity) \
   const struct Tux64BootStage1FbconText \
   identifier = { \
      .ptr        = identifier_ptr , \
      .length     = TUX64_LITERAL_UINT8( identifier_length ), \
      .capacity   = TUX64_LITERAL_UINT8( identifier_capacity ) \
   }

/* defining these separately instead of in an array allows dead code */
/* elimination to work better.  also, the compiler tends to place these */
/* close to each other, so we still get good data locality.  if caching */
/* becomes a problem, we can just manually place them in a separate section. */
TUX64_BOOT_STAGE1_STRINGS_TEXT_DEFINE(
   tux64_boot_stage1_strings_splash,
   tux64_boot_stage1_strings_splash_data,
   TUX64_BOOT_STAGE1_STRINGS_SPLASH_LENGTH,
   TUX64_BOOT_STAGE1_STRINGS_SPLASH_LENGTH
);
TUX64_BOOT_STAGE1_STRINGS_TEXT_DEFINE(
   tux64_boot_stage1_strings_memory_total,
   tux64_boot_stage1_strings_memory_total_data,
   TUX64_BOOT_STAGE1_STRINGS_MEMORY_TOTAL_LENGTH,
   TUX64_BOOT_STAGE1_STRINGS_MEMORY_TOTAL_LENGTH + TUX64_BOOT_STAGE1_FORMAT_BUFFER_CHARACTERS_MIB
);
TUX64_BOOT_STAGE1_STRINGS_TEXT_DEFINE(
   tux64_boot_stage1_strings_memory_free,
   tux64_boot_stage1_strings_memory_free_data,
   TUX64_BOOT_STAGE1_STRINGS_MEMORY_FREE_LENGTH,
   TUX64_BOOT_STAGE1_STRINGS_MEMORY_FREE_LENGTH + TUX64_BOOT_STAGE1_FORMAT_BUFFER_CHARACTERS_MIB
);
TUX64_BOOT_STAGE1_STRINGS_TEXT_DEFINE(
   tux64_boot_stage1_strings_kernel_image,
   tux64_boot_stage1_strings_kernel_image_data,
   TUX64_BOOT_STAGE1_STRINGS_KERNEL_IMAGE_LENGTH,
   TUX64_BOOT_STAGE1_STRINGS_KERNEL_IMAGE_LENGTH + TUX64_BOOT_STAGE1_FORMAT_BUFFER_CHARACTERS_MIB
);
TUX64_BOOT_STAGE1_STRINGS_TEXT_DEFINE(
   tux64_boot_stage1_strings_initramfs_image,
   tux64_boot_stage1_strings_initramfs_image_data,
   TUX64_BOOT_STAGE1_STRINGS_INITRAMFS_IMAGE_LENGTH,
   TUX64_BOOT_STAGE1_STRINGS_INITRAMFS_IMAGE_LENGTH + TUX64_BOOT_STAGE1_FORMAT_BUFFER_CHARACTERS_MIB
);
TUX64_BOOT_STAGE1_STRINGS_TEXT_DEFINE(
   tux64_boot_stage1_strings_no_checksum,
   tux64_boot_stage1_strings_no_checksum_data,
   TUX64_BOOT_STAGE1_STRINGS_NO_CHECKSUM_LENGTH,
   TUX64_BOOT_STAGE1_STRINGS_NO_CHECKSUM_LENGTH
);
TUX64_BOOT_STAGE1_STRINGS_TEXT_DEFINE(
   tux64_boot_stage1_strings_hello_world,
   tux64_boot_stage1_strings_hello_world_data,
   TUX64_BOOT_STAGE1_STRINGS_HELLO_WORLD_LENGTH,
   TUX64_BOOT_STAGE1_STRINGS_HELLO_WORLD_LENGTH + TUX64_BOOT_STAGE1_FORMAT_BUFFER_CHARACTERS_PERCENTAGE
);

