/*----------------------------------------------------------------------------*/
/*                          Copyright (C) Tux64 2025                          */
/*                    https://github.com/bradleycha/tux64                     */
/*----------------------------------------------------------------------------*/
/* lib/src/platform-n64/memory-map.h - CPU memory map constants.              */
/*----------------------------------------------------------------------------*/

#ifndef _TUX64_PLATFORM_N64_MEMORY_MAP_H
#define _TUX64_PLATFORM_N64_MEMORY_MAP_H
/*----------------------------------------------------------------------------*/

#include "tux64/tux64.h"

/* MMU address segments which change how virtual addresses are mapped to */
/* physical addresses. */
#define TUX64_PLATFORM_N64_MEMORY_MAP_ADDRESS_SEGMENT_USER_TLB\
   (0x00000000u)
#define TUX64_PLATFORM_N64_MEMORY_MAP_ADDRESS_SEGMENT_DIRECT_CACHED\
   (0x80000000u)
#define TUX64_PLATFORM_N64_MEMORY_MAP_ADDRESS_SEGMENT_DIRECT_UNCACHED\
   (0xa0000000u)
#define TUX64_PLATFORM_N64_MEMORY_MAP_ADDRESS_SEGMENT_SUPERVISOR_TLB\
   (0xc0000000u)
#define TUX64_PLATFORM_N64_MEMORY_MAP_ADDRESS_SEGMENT_KERNEL_TLB\
   (0xe0000000u)

/* physical memory addresses which map directly to the console's address */
/* space. */
#define TUX64_PLATFORM_N64_MEMORY_MAP_ADDRESS_PHYSICAL_RDRAM\
   (0x00000000u)
#define TUX64_PLATFORM_N64_MEMORY_MAP_ADDRESS_PHYSICAL_RDRAM_REGISTERS\
   (0x03f00000u)
#define TUX64_PLATFORM_N64_MEMORY_MAP_ADDRESS_PHYSICAL_RDRAM_REGISTERS_BROADCAST\
   (0x03f80000u)
#define TUX64_PLATFORM_N64_MEMORY_MAP_ADDRESS_PHYSICAL_RSP_DMEM\
   (0x04000000u)
#define TUX64_PLATFORM_N64_MEMORY_MAP_ADDRESS_PHYSICAL_RSP_IMEM\
   (0x04001000u)
#define TUX64_PLATFORM_N64_MEMORY_MAP_ADDRESS_PHYSICAL_RSP_REGISTERS\
   (0x04040000u)
#define TUX64_PLATFORM_N64_MEMORY_MAP_ADDRESS_PHYSICAL_RDP_REGISTERS\
   (0x04100000u)
#define TUX64_PLATFORM_N64_MEMORY_MAP_ADDRESS_PHYSICAL_MI\
   (0x04300000u)
#define TUX64_PLATFORM_N64_MEMORY_MAP_ADDRESS_PHYSICAL_VI\
   (0x04400000u)
#define TUX64_PLATFORM_N64_MEMORY_MAP_ADDRESS_PHYSICAL_AI\
   (0x04500000u)
#define TUX64_PLATFORM_N64_MEMORY_MAP_ADDRESS_PHYSICAL_PI\
   (0x04600000u)
#define TUX64_PLATFORM_N64_MEMORY_MAP_ADDRESS_PHYSICAL_RI\
   (0x04700000u)
#define TUX64_PLATFORM_N64_MEMORY_MAP_ADDRESS_PHYSICAL_SI\
   (0x04800000u)
#define TUX64_PLATFORM_N64_MEMORY_MAP_ADDRESS_PHYSICAL_64DD_REGISTERS\
   (0x05000000u)
#define TUX64_PLATFORM_N64_MEMORY_MAP_ADDRESS_PHYSICAL_64DD_IPL_ROM\
   (0x06000000u)
#define TUX64_PLATFORM_N64_MEMORY_MAP_ADDRESS_PHYSICAL_CARTRIDGE_RAM\
   (0x08000000u)
#define TUX64_PLATFORM_N64_MEMORY_MAP_ADDRESS_PHYSICAL_CARTRIDGE_ROM\
   (0x10000000u)
#define TUX64_PLATFORM_N64_MEMORY_MAP_ADDRESS_PHYSICAL_PIF_ROM\
   (0x1fc00000u)
#define TUX64_PLATFORM_N64_MEMORY_MAP_ADDRESS_PHYSICAL_PIF_RAM\
   (0x1fc007c0u)

/* virtual addresses which can be used as an address from the CPU.  all of */
/* these will use the uncached direct segment, as user programs should never */
/* access these directly. RDRAM is the exception, with a cached segment */
/* available.  Only RDRAM supports cached access, so it's the only cached */
/* virtual address. */
#define TUX64_PLATFORM_N64_MEMORY_MAP_ADDRESS_RDRAM_CACHED\
   (\
      TUX64_PLATFORM_N64_MEMORY_MAP_ADDRESS_SEGMENT_DIRECT_CACHED + \
      TUX64_PLATFORM_N64_MEMORY_MAP_ADDRESS_PHYSICAL_RDRAM\
   )
#define TUX64_PLATFORM_N64_MEMORY_MAP_ADDRESS_RDRAM_UNCACHED\
   (\
      TUX64_PLATFORM_N64_MEMORY_MAP_ADDRESS_SEGMENT_DIRECT_UNCACHED + \
      TUX64_PLATFORM_N64_MEMORY_MAP_ADDRESS_PHYSICAL_RDRAM\
   )
#define TUX64_PLATFORM_N64_MEMORY_MAP_ADDRESS_RDRAM_REGISTERS\
   (\
      TUX64_PLATFORM_N64_MEMORY_MAP_ADDRESS_SEGMENT_DIRECT_UNCACHED + \
      TUX64_PLATFORM_N64_MEMORY_MAP_ADDRESS_PHYSICAL_RDRAM_REGISTERS\
   )
#define TUX64_PLATFORM_N64_MEMORY_MAP_ADDRESS_RDRAM_REGISTERS_BROADCAST\
   (\
      TUX64_PLATFORM_N64_MEMORY_MAP_ADDRESS_SEGMENT_DIRECT_UNCACHED + \
      TUX64_PLATFORM_N64_MEMORY_MAP_ADDRESS_PHYSICAL_RDRAM_REGISTERS_BROADCAST\
   )
#define TUX64_PLATFORM_N64_MEMORY_MAP_ADDRESS_RSP_DMEM\
   (\
      TUX64_PLATFORM_N64_MEMORY_MAP_ADDRESS_SEGMENT_DIRECT_UNCACHED + \
      TUX64_PLATFORM_N64_MEMORY_MAP_ADDRESS_PHYSICAL_RSP_DMEM\
   )
#define TUX64_PLATFORM_N64_MEMORY_MAP_ADDRESS_RSP_IMEM\
   (\
      TUX64_PLATFORM_N64_MEMORY_MAP_ADDRESS_SEGMENT_DIRECT_UNCACHED + \
      TUX64_PLATFORM_N64_MEMORY_MAP_ADDRESS_PHYSICAL_RSP_IMEM\
   )
#define TUX64_PLATFORM_N64_MEMORY_MAP_ADDRESS_RSP_REGISTERS\
   (\
      TUX64_PLATFORM_N64_MEMORY_MAP_ADDRESS_SEGMENT_DIRECT_UNCACHED + \
      TUX64_PLATFORM_N64_MEMORY_MAP_ADDRESS_PHYSICAL_RSP_REGISTERS\
   )
#define TUX64_PLATFORM_N64_MEMORY_MAP_ADDRESS_RDP_REGISTERS\
   (\
      TUX64_PLATFORM_N64_MEMORY_MAP_ADDRESS_SEGMENT_DIRECT_UNCACHED + \
      TUX64_PLATFORM_N64_MEMORY_MAP_ADDRESS_PHYSICAL_RDP_REGISTERS\
   )
#define TUX64_PLATFORM_N64_MEMORY_MAP_ADDRESS_MI\
   (\
      TUX64_PLATFORM_N64_MEMORY_MAP_ADDRESS_SEGMENT_DIRECT_UNCACHED + \
      TUX64_PLATFORM_N64_MEMORY_MAP_ADDRESS_PHYSICAL_MI\
   )
#define TUX64_PLATFORM_N64_MEMORY_MAP_ADDRESS_VI\
   (\
      TUX64_PLATFORM_N64_MEMORY_MAP_ADDRESS_SEGMENT_DIRECT_UNCACHED + \
      TUX64_PLATFORM_N64_MEMORY_MAP_ADDRESS_PHYSICAL_VI\
   )
#define TUX64_PLATFORM_N64_MEMORY_MAP_ADDRESS_AI\
   (\
      TUX64_PLATFORM_N64_MEMORY_MAP_ADDRESS_SEGMENT_DIRECT_UNCACHED + \
      TUX64_PLATFORM_N64_MEMORY_MAP_ADDRESS_PHYSICAL_AI\
   )
#define TUX64_PLATFORM_N64_MEMORY_MAP_ADDRESS_PI\
   (\
      TUX64_PLATFORM_N64_MEMORY_MAP_ADDRESS_SEGMENT_DIRECT_UNCACHED + \
      TUX64_PLATFORM_N64_MEMORY_MAP_ADDRESS_PHYSICAL_PI\
   )
#define TUX64_PLATFORM_N64_MEMORY_MAP_ADDRESS_RI\
   (\
      TUX64_PLATFORM_N64_MEMORY_MAP_ADDRESS_SEGMENT_DIRECT_UNCACHED + \
      TUX64_PLATFORM_N64_MEMORY_MAP_ADDRESS_PHYSICAL_RI\
   )
#define TUX64_PLATFORM_N64_MEMORY_MAP_ADDRESS_SI\
   (\
      TUX64_PLATFORM_N64_MEMORY_MAP_ADDRESS_SEGMENT_DIRECT_UNCACHED + \
      TUX64_PLATFORM_N64_MEMORY_MAP_ADDRESS_PHYSICAL_SI\
   )
#define TUX64_PLATFORM_N64_MEMORY_MAP_ADDRESS_64DD_REGISTERS\
   (\
      TUX64_PLATFORM_N64_MEMORY_MAP_ADDRESS_SEGMENT_DIRECT_UNCACHED + \
      TUX64_PLATFORM_N64_MEMORY_MAP_ADDRESS_PHYSICAL_64DD_REGISTERS\
   )
#define TUX64_PLATFORM_N64_MEMORY_MAP_ADDRESS_64DD_IPL_ROM\
   (\
      TUX64_PLATFORM_N64_MEMORY_MAP_ADDRESS_SEGMENT_DIRECT_UNCACHED + \
      TUX64_PLATFORM_N64_MEMORY_MAP_ADDRESS_PHYSICAL_64DD_IPL_ROM\
   )
#define TUX64_PLATFORM_N64_MEMORY_MAP_ADDRESS_CARTRIDGE_RAM\
   (\
      TUX64_PLATFORM_N64_MEMORY_MAP_ADDRESS_SEGMENT_DIRECT_UNCACHED + \
      TUX64_PLATFORM_N64_MEMORY_MAP_ADDRESS_PHYSICAL_CARTRIDGE_RAM\
   )
#define TUX64_PLATFORM_N64_MEMORY_MAP_ADDRESS_CARTRIDGE_ROM\
   (\
      TUX64_PLATFORM_N64_MEMORY_MAP_ADDRESS_SEGMENT_DIRECT_UNCACHED + \
      TUX64_PLATFORM_N64_MEMORY_MAP_ADDRESS_PHYSICAL_CARTRIDGE_ROM\
   )
#define TUX64_PLATFORM_N64_MEMORY_MAP_ADDRESS_PIF_ROM\
   (\
      TUX64_PLATFORM_N64_MEMORY_MAP_ADDRESS_SEGMENT_DIRECT_UNCACHED + \
      TUX64_PLATFORM_N64_MEMORY_MAP_ADDRESS_PHYSICAL_PIF_ROM\
   )
#define TUX64_PLATFORM_N64_MEMORY_MAP_ADDRESS_PIF_RAM\
   (\
      TUX64_PLATFORM_N64_MEMORY_MAP_ADDRESS_SEGMENT_DIRECT_UNCACHED + \
      TUX64_PLATFORM_N64_MEMORY_MAP_ADDRESS_PHYSICAL_PIF_RAM\
   )

/*----------------------------------------------------------------------------*/
#endif /* _TUX64_PLATFORM_N64_MEMORY_MAP_H */

