/*----------------------------------------------------------------------------*/
/*                          Copyright (C) Tux64 2025                          */
/*                    https://github.com/bradleycha/tux64                     */
/*----------------------------------------------------------------------------*/
/* develop/ldscripts/tux64.ld - Main linker script used to define external    */
/*    MMIO, variables, and setup for external projects.                       */
/*----------------------------------------------------------------------------*/

INCLUDE tux64/platform_n64/memory_map.ld
INCLUDE tux64/platform_n64/mmio.ld

