/*----------------------------------------------------------------------------*/
/*                          Copyright (C) Tux64 2025                          */
/*                    https://github.com/bradleycha/tux64                     */
/*----------------------------------------------------------------------------*/
/* lib/src/platform-n64/platform-n64.ld - Linker script to provide            */
/*    definitions for the Nintendo 64, intended to be used in a bare-metal    */
/*    environment.                                                            */
/*----------------------------------------------------------------------------*/

INCLUDE memory_map.ld
INCLUDE mmio.ld

