/*----------------------------------------------------------------------------*/
/*                          Copyright (C) Tux64 2025                          */
/*                    https://github.com/bradleycha/tux64                     */
/*----------------------------------------------------------------------------*/
/* fontcompiler/src/tux64-fontcompiler/generator.h - Header for font map      */
/*    image data C source code generation.                                    */
/*----------------------------------------------------------------------------*/

#ifndef _TUX64_FONTCOMPILER_GENERATOR_H
#define _TUX64_FONTCOMPILER_GENERATOR_H
/*----------------------------------------------------------------------------*/

#include "tux64-fontcompiler/tux64-fontcompiler.h"

enum Tux64FontCompilerGeneratorParseStatus {
   TUX64_FONTCOMPILER_GENERATOR_PARSE_STATUS_OK,
   TUX64_FONTCOMPILER_GENERATOR_PARSE_STATUS_OUT_OF_MEMORY,
   TUX64_FONTCOMPILER_GENERATOR_PARSE_STATUS_INVALID_IMAGE_FORMAT
};

struct Tux64FontCompilerGeneratorParsePayloadOk {
   Tux64UInt8 * data;
   Tux64UInt32 bytes;
};

union Tux64FontCompilerGeneratorParsePayload {
   struct Tux64FontCompilerGeneratorParsePayloadOk ok;
};

struct Tux64FontCompilerGeneratorParseResult {
   enum Tux64FontCompilerGeneratorParseStatus status;
   union Tux64FontCompilerGeneratorParsePayload payload;
};

/*----------------------------------------------------------------------------*/
/* Converts raw RGB888 image data to C source code which encodes a font map   */
/* compatible with tux64-boot.  The returned 'ok' variant must be manually    */
/* freed with free() when this function succeeds.  The identifier for the     */
/* generated byte array will be 'identifier'.                                 */
/*----------------------------------------------------------------------------*/
struct Tux64FontCompilerGeneratorParseResult
tux64_fontcompiler_generator_parse(
   const Tux64UInt8 * data,
   Tux64UInt32 bytes,
   const struct Tux64String * identifier
);

/*----------------------------------------------------------------------------*/
#endif /* _TUX64_FONTCOMPILER_GENERATOR_H */

