/*----------------------------------------------------------------------------*/
/*                          Copyright (C) Tux64 2025                          */
/*                    https://github.com/bradleycha/tux64                     */
/*----------------------------------------------------------------------------*/
/* lib/src/platform_n64/platform_n64.ld - Linker script to provide            */
/*    definitions for the Nintendo 64, intended to be used in a bare-metal    */
/*    environment.                                                            */
/*----------------------------------------------------------------------------*/

INCLUDE platform_n64/memory_map.ld
INCLUDE platform_n64/mmio.ld

