/*----------------------------------------------------------------------------*/
/*                          Copyright (C) Tux64 2026                          */
/*                    https://github.com/bradleycha/tux64                     */
/*----------------------------------------------------------------------------*/
/* rescompiler/imagecompiler/src/tux64-imagecompiler/formatter.h -            */
/*    Implementations for C source code formatter.                            */
/*----------------------------------------------------------------------------*/

#include "tux64-imagecompiler/tux64-imagecompiler.h"
#include "tux64-imagecompiler/formatter.h"

#include <tux64/memory.h>
#include "tux64-imagecompiler/encoder.h"

#include <stdlib.h>

#define TUX64_IMAGECOMPILER_FORMATTER_PRELUDE \
   "/* C source code generated by " TUX64_IMAGECOMPILER_PACKAGE_NAME " version " TUX64_IMAGECOMPILER_PACKAGE_VERSION " */\n"
#define TUX64_IMAGECOMPILER_FORMATTER_DEFINE_PREFIX \
   "#define "
#define TUX64_IMAGECOMPILER_FORMATTER_DEFINE_SUFFIX \
   " \\\n"
#define TUX64_IMAGECOMPILER_FORMATTER_ENTRY_UINT8_PREFIX \
   "   TUX64_LITERAL_UINT8(0x"
#define TUX64_IMAGECOMPILER_FORMATTER_ENTRY_UINT16_PREFIX \
   "   TUX64_LITERAL_UINT16(0x"
#define TUX64_IMAGECOMPILER_FORMATTER_ENTRY_SUFFIX_NEWLINE \
   "u), \\\n"
#define TUX64_IMAGECOMPILER_FORMATTER_ENTRY_SUFFIX_FINAL \
   "u)\n"

#define TUX64_IMAGECOMPILER_FORMATTER_PRELUDE_CHARACTERS \
   TUX64_STRING_CHARACTERS(TUX64_IMAGECOMPILER_FORMATTER_PRELUDE)
#define TUX64_IMAGECOMPILER_FORMATTER_DEFINE_PREFIX_CHARACTERS \
   TUX64_STRING_CHARACTERS(TUX64_IMAGECOMPILER_FORMATTER_DEFINE_PREFIX)
#define TUX64_IMAGECOMPILER_FORMATTER_DEFINE_SUFFIX_CHARACTERS \
   TUX64_STRING_CHARACTERS(TUX64_IMAGECOMPILER_FORMATTER_DEFINE_SUFFIX)
#define TUX64_IMAGECOMPILER_FORMATTER_ENTRY_UINT8_PREFIX_CHARACTERS \
   TUX64_STRING_CHARACTERS(TUX64_IMAGECOMPILER_FORMATTER_ENTRY_UINT8_PREFIX)
#define TUX64_IMAGECOMPILER_FORMATTER_ENTRY_UINT16_PREFIX_CHARACTERS \
   TUX64_STRING_CHARACTERS(TUX64_IMAGECOMPILER_FORMATTER_ENTRY_UINT16_PREFIX)
#define TUX64_IMAGECOMPILER_FORMATTER_ENTRY_SUFFIX_NEWLINE_CHARACTERS \
   TUX64_STRING_CHARACTERS(TUX64_IMAGECOMPILER_FORMATTER_ENTRY_SUFFIX_NEWLINE)
#define TUX64_IMAGECOMPILER_FORMATTER_ENTRY_SUFFIX_FINAL_CHARACTERS \
   TUX64_STRING_CHARACTERS(TUX64_IMAGECOMPILER_FORMATTER_ENTRY_SUFFIX_FINAL)


static Tux64UInt32
tux64_imagecompiler_formatter_calculate_output_length_identifier(
   const struct Tux64String * identifier
) {
   Tux64UInt32 characters;

   characters = TUX64_LITERAL_UINT32(0u);

   characters += TUX64_LITERAL_UINT32(TUX64_IMAGECOMPILER_FORMATTER_DEFINE_PREFIX_CHARACTERS);
   characters += identifier->characters;
   characters += TUX64_LITERAL_UINT32(TUX64_IMAGECOMPILER_FORMATTER_DEFINE_SUFFIX_CHARACTERS);

   return characters;
}

static Tux64UInt32
tux64_imagecompiler_formatter_calculate_output_length_pixels(
   const struct Tux64ImageCompilerCompressorImageData * image,
   const struct Tux64String * identifier_pixels
) {
   Tux64UInt32 characters;

   characters = TUX64_LITERAL_UINT32(0u);

   characters += tux64_imagecompiler_formatter_calculate_output_length_identifier(identifier_pixels);
   characters += TUX64_LITERAL_UINT32(
      (
         TUX64_IMAGECOMPILER_FORMATTER_ENTRY_UINT8_PREFIX_CHARACTERS +
         2u +
         TUX64_IMAGECOMPILER_FORMATTER_ENTRY_SUFFIX_NEWLINE_CHARACTERS
      ) * (image->length - 1u)
   );
   characters += TUX64_LITERAL_UINT32(
      TUX64_IMAGECOMPILER_FORMATTER_ENTRY_UINT8_PREFIX_CHARACTERS +
      2u +
      TUX64_IMAGECOMPILER_FORMATTER_ENTRY_SUFFIX_FINAL_CHARACTERS
   );

   return characters;
}

static Tux64UInt32
tux64_imagecompiler_formatter_calculate_output_length_color_table(
   const struct Tux64String * identifier_color_table
) {
   Tux64UInt32 characters;

   characters = TUX64_LITERAL_UINT32(0u);

   characters += tux64_imagecompiler_formatter_calculate_output_length_identifier(identifier_color_table);
   characters += TUX64_LITERAL_UINT32(
      (
         TUX64_IMAGECOMPILER_FORMATTER_ENTRY_UINT16_PREFIX_CHARACTERS +
         4u +
         TUX64_IMAGECOMPILER_FORMATTER_ENTRY_SUFFIX_NEWLINE_CHARACTERS
      ) * (TUX64_IMAGECOMPILER_ENCODER_COLORS - 1u)
   );
   characters += TUX64_LITERAL_UINT32(
      TUX64_IMAGECOMPILER_FORMATTER_ENTRY_UINT16_PREFIX_CHARACTERS +
      4u +
      TUX64_IMAGECOMPILER_FORMATTER_ENTRY_SUFFIX_FINAL_CHARACTERS
   );

   return characters;
}

static Tux64UInt32
tux64_imagecompiler_formatter_calculate_output_length(
   const struct Tux64ImageCompilerCompressorImageData * image,
   const struct Tux64String * identifier_pixels,
   const struct Tux64String * identifier_color_table
) {
   Tux64UInt32 characters;

   characters = TUX64_LITERAL_UINT32(0u);

   characters += TUX64_LITERAL_UINT32(TUX64_IMAGECOMPILER_FORMATTER_PRELUDE_CHARACTERS);
   characters += tux64_imagecompiler_formatter_calculate_output_length_pixels(image, identifier_pixels);
   characters += tux64_imagecompiler_formatter_calculate_output_length_color_table(identifier_color_table);

   return characters;
}

static Tux64UInt8 *
tux64_imagecompiler_formatter_generate_prelude(
   Tux64UInt8 * output
) {
   Tux64UInt8 * iter_output;

   iter_output = output;

   tux64_memory_copy(
      iter_output,
      TUX64_IMAGECOMPILER_FORMATTER_PRELUDE,
      TUX64_LITERAL_UINT32(TUX64_IMAGECOMPILER_FORMATTER_PRELUDE_CHARACTERS)
   );
   iter_output += TUX64_LITERAL_UINT32(TUX64_IMAGECOMPILER_FORMATTER_PRELUDE_CHARACTERS);

   return iter_output;
}

static Tux64UInt8 *
tux64_imagecompiler_formatter_generate_identifier(
   Tux64UInt8 * output,
   const struct Tux64String * identifier
) {
   Tux64UInt8 * iter_output;

   iter_output = output;

   tux64_memory_copy(
      iter_output,
      TUX64_IMAGECOMPILER_FORMATTER_DEFINE_PREFIX,
      TUX64_LITERAL_UINT32(TUX64_IMAGECOMPILER_FORMATTER_DEFINE_PREFIX_CHARACTERS)
   );
   iter_output += TUX64_LITERAL_UINT32(TUX64_IMAGECOMPILER_FORMATTER_DEFINE_PREFIX_CHARACTERS);

   tux64_memory_copy(
      iter_output,
      identifier->ptr,
      identifier->characters * TUX64_LITERAL_UINT32(sizeof(char))
   );
   iter_output += (identifier->characters * TUX64_LITERAL_UINT32(sizeof(char)));

   tux64_memory_copy(
      iter_output,
      TUX64_IMAGECOMPILER_FORMATTER_DEFINE_SUFFIX,
      TUX64_LITERAL_UINT32(TUX64_IMAGECOMPILER_FORMATTER_DEFINE_SUFFIX_CHARACTERS)
   );
   iter_output += TUX64_LITERAL_UINT32(TUX64_IMAGECOMPILER_FORMATTER_DEFINE_SUFFIX_CHARACTERS);

   return iter_output;
}

static Tux64UInt8
tux64_imagecompiler_formatter_generate_nibble(
   Tux64UInt8 nibble
) {
   if (nibble <= TUX64_LITERAL_UINT8(9u)) {
      return (Tux64UInt8)('0' + nibble);
   }

   return (Tux64UInt8)('a' + nibble - TUX64_LITERAL_UINT8(10u));
}

static Tux64UInt8 *
tux64_imagecompiler_formatter_generate_pixels_entry(
   Tux64UInt8 * output,
   Tux64UInt8 pixel_tuple,
   const char * suffix_ptr,
   Tux64UInt32 suffix_characters
) {
   Tux64UInt8 * iter_output;

   iter_output = output;

   tux64_memory_copy(
      iter_output,
      TUX64_IMAGECOMPILER_FORMATTER_ENTRY_UINT8_PREFIX,
      TUX64_LITERAL_UINT32(TUX64_IMAGECOMPILER_FORMATTER_ENTRY_UINT8_PREFIX_CHARACTERS)
   );
   iter_output += TUX64_LITERAL_UINT32(TUX64_IMAGECOMPILER_FORMATTER_ENTRY_UINT8_PREFIX_CHARACTERS);

   *iter_output++ = tux64_imagecompiler_formatter_generate_nibble((pixel_tuple >> TUX64_LITERAL_UINT8( 4u)) & TUX64_LITERAL_UINT8(0x0fu));
   *iter_output++ = tux64_imagecompiler_formatter_generate_nibble((pixel_tuple >> TUX64_LITERAL_UINT8( 0u)) & TUX64_LITERAL_UINT8(0x0fu));

   tux64_memory_copy(
      iter_output,
      suffix_ptr,
      suffix_characters * TUX64_LITERAL_UINT32(sizeof(char))
   );
   iter_output += (suffix_characters * TUX64_LITERAL_UINT32(sizeof(char)));

   return iter_output;
}

static Tux64UInt8 *
tux64_imagecompiler_formatter_generate_pixels(
   Tux64UInt8 * output,
   const struct Tux64ImageCompilerCompressorImageData * image,
   const struct Tux64String * identifier_pixels
) {
   Tux64UInt8 * iter_output;
   const Tux64UInt8 * iter_pixel_tuple;
   Tux64UInt32 i;

   iter_output = output;

   iter_output = tux64_imagecompiler_formatter_generate_identifier(iter_output, identifier_pixels);

   i = (image->length - TUX64_LITERAL_UINT32(1u));
   iter_pixel_tuple = image->bytes;

   do {
      iter_output = tux64_imagecompiler_formatter_generate_pixels_entry(
         iter_output,
         *iter_pixel_tuple,
         TUX64_IMAGECOMPILER_FORMATTER_ENTRY_SUFFIX_NEWLINE,
         TUX64_LITERAL_UINT32(TUX64_IMAGECOMPILER_FORMATTER_ENTRY_SUFFIX_NEWLINE_CHARACTERS)
      );

      iter_pixel_tuple++;
      i--;
   } while (i != TUX64_LITERAL_UINT32(0u));

   iter_output = tux64_imagecompiler_formatter_generate_pixels_entry(
      iter_output,
      *iter_pixel_tuple,
      TUX64_IMAGECOMPILER_FORMATTER_ENTRY_SUFFIX_FINAL,
      TUX64_LITERAL_UINT32(TUX64_IMAGECOMPILER_FORMATTER_ENTRY_SUFFIX_FINAL_CHARACTERS)

   );

   return iter_output;
}

static Tux64UInt8 *
tux64_imagecompiler_formatter_generate_color_table_entry(
   Tux64UInt8 * output,
   Tux64UInt16 color,
   const char * suffix_ptr,
   Tux64UInt32 suffix_characters
) {
   Tux64UInt8 * iter_output;

   iter_output = output;

   tux64_memory_copy(
      iter_output,
      TUX64_IMAGECOMPILER_FORMATTER_ENTRY_UINT16_PREFIX,
      TUX64_LITERAL_UINT32(TUX64_IMAGECOMPILER_FORMATTER_ENTRY_UINT16_PREFIX_CHARACTERS)
   );
   iter_output += TUX64_LITERAL_UINT32(TUX64_IMAGECOMPILER_FORMATTER_ENTRY_UINT16_PREFIX_CHARACTERS);

   *iter_output++ = tux64_imagecompiler_formatter_generate_nibble((color >> TUX64_LITERAL_UINT8(12u)) & TUX64_LITERAL_UINT16(0x000fu));
   *iter_output++ = tux64_imagecompiler_formatter_generate_nibble((color >> TUX64_LITERAL_UINT8( 8u)) & TUX64_LITERAL_UINT16(0x000fu));
   *iter_output++ = tux64_imagecompiler_formatter_generate_nibble((color >> TUX64_LITERAL_UINT8( 4u)) & TUX64_LITERAL_UINT16(0x000fu));
   *iter_output++ = tux64_imagecompiler_formatter_generate_nibble((color >> TUX64_LITERAL_UINT8( 0u)) & TUX64_LITERAL_UINT16(0x000fu));

   tux64_memory_copy(
      iter_output,
      suffix_ptr,
      suffix_characters * TUX64_LITERAL_UINT32(sizeof(char))
   );
   iter_output += (suffix_characters * TUX64_LITERAL_UINT32(sizeof(char)));

   return iter_output;
}

static Tux64UInt8 *
tux64_imagecompiler_formatter_generate_color_table(
   Tux64UInt8 * output,
   const Tux64UInt16 color_table [TUX64_IMAGECOMPILER_ENCODER_COLORS],
   const struct Tux64String * identifier_color_table
) {
   Tux64UInt8 * iter_output;
   const Tux64UInt16 * iter_color_table;
   Tux64UInt32 i;

   iter_output = output;

   iter_output = tux64_imagecompiler_formatter_generate_identifier(iter_output, identifier_color_table);

   i = (TUX64_IMAGECOMPILER_ENCODER_COLORS - 1u);
   iter_color_table = color_table;

   do {
      iter_output = tux64_imagecompiler_formatter_generate_color_table_entry(
         iter_output,
         *iter_color_table,
         TUX64_IMAGECOMPILER_FORMATTER_ENTRY_SUFFIX_NEWLINE,
         TUX64_LITERAL_UINT32(TUX64_IMAGECOMPILER_FORMATTER_ENTRY_SUFFIX_NEWLINE_CHARACTERS)
      );

      iter_color_table++;
      i--;
   } while (i != TUX64_LITERAL_UINT32(0u));

   iter_output = tux64_imagecompiler_formatter_generate_color_table_entry(
      iter_output,
      *iter_color_table,
      TUX64_IMAGECOMPILER_FORMATTER_ENTRY_SUFFIX_FINAL,
      TUX64_LITERAL_UINT32(TUX64_IMAGECOMPILER_FORMATTER_ENTRY_SUFFIX_FINAL_CHARACTERS)
   );

   return iter_output;
}

static void
tux64_imagecompiler_formatter_generate_allocated(
   const struct Tux64ImageCompilerCompressorImageData * image,
   const Tux64UInt16 color_table [TUX64_IMAGECOMPILER_ENCODER_COLORS],
   const struct Tux64String * identifier_pixels,
   const struct Tux64String * identifier_color_table,
   Tux64UInt8 * output
) {
   Tux64UInt8 * iter_output;

   iter_output = output;

   iter_output = tux64_imagecompiler_formatter_generate_prelude(iter_output);
   iter_output = tux64_imagecompiler_formatter_generate_pixels(iter_output, image, identifier_pixels);
   iter_output = tux64_imagecompiler_formatter_generate_color_table(iter_output, color_table, identifier_color_table);

   return;
}

struct Tux64ImageCompilerFormatterGenerateResult
tux64_imagecompiler_formatter_generate(
   const struct Tux64ImageCompilerCompressorImageData * image,
   const Tux64UInt16 color_table [TUX64_IMAGECOMPILER_ENCODER_COLORS],
   const struct Tux64String * identifier_pixels,
   const struct Tux64String * identifier_color_table
) {
   struct Tux64ImageCompilerFormatterGenerateResult result;
   Tux64UInt32 output_bytes;
   Tux64UInt8 * output_data;

   output_bytes = tux64_imagecompiler_formatter_calculate_output_length(
      image,
      identifier_pixels,
      identifier_color_table
   ) * TUX64_LITERAL_UINT32(sizeof(char));

   output_data = (Tux64UInt8 *)malloc(output_bytes);
   if (output_data == NULL) {
      result.status = TUX64_IMAGECOMPILER_FORMATTER_GENERATE_STATUS_OUT_OF_MEMORY;
      return result;
   }

   tux64_imagecompiler_formatter_generate_allocated(
      image,
      color_table,
      identifier_pixels,
      identifier_color_table,
      output_data
   );
   
   result.status = TUX64_IMAGECOMPILER_FORMATTER_GENERATE_STATUS_OK;
   result.payload.ok.data = output_data;
   result.payload.ok.bytes = output_bytes;
   return result;
}

