/*----------------------------------------------------------------------------*/
/*                          Copyright (C) Tux64 2025                          */
/*                    https://github.com/bradleycha/tux64                     */
/*----------------------------------------------------------------------------*/
/* lib/src/tux64/platform/mips/n64/boot.ld - Linker script constants for the  */
/*    bootloader header.                                                      */
/*----------------------------------------------------------------------------*/

/* the length of the bootloader header, in bytes */
TUX64_PLATFORM_MIPS_N64_BOOT_HEADER_LENGTH_BYTES
   = 0x00000038;

