/*----------------------------------------------------------------------------*/
/*                       Copyright (C) Tux64 2025, 2026                       */
/*                    https://github.com/bradleycha/tux64                     */
/*----------------------------------------------------------------------------*/
/* lib/src/tux64/platform/mips/n64/memory-map.ld.h - CPU memory map linker    */
/*    script constants.                                                       */
/*----------------------------------------------------------------------------*/

#ifndef _TUX64_PLATFORM_MIPS_N64_MEMORY_MAP_LD_H
#define _TUX64_PLATFORM_MIPS_N64_MEMORY_MAP_LD_H
/*----------------------------------------------------------------------------*/

#include "tux64/tux64.h"
#include "tux64/platform/mips/n64/memory-map.h"

MEMORY
{
   TUX64_PLATFORM_MIPS_N64_MEMORY_MAP_LAYOUT_RDRAM_CACHED
      (rwx)
      : ORIGIN = TUX64_PLATFORM_MIPS_N64_MEMORY_MAP_ADDRESS_RDRAM_CACHED,
      LENGTH = 0x03f00000
   TUX64_PLATFORM_MIPS_N64_MEMORY_MAP_LAYOUT_RDRAM_UNCACHED
      (rwx)
      : ORIGIN = TUX64_PLATFORM_MIPS_N64_MEMORY_MAP_ADDRESS_RDRAM_UNCACHED,
      LENGTH = 0x03f00000
   TUX64_PLATFORM_MIPS_N64_MEMORY_MAP_LAYOUT_RDRAM_REGISTERS
      (rw)
      : ORIGIN = TUX64_PLATFORM_MIPS_N64_MEMORY_MAP_ADDRESS_RDRAM_REGISTERS,
      LENGTH = 0x00080000
   TUX64_PLATFORM_MIPS_N64_MEMORY_MAP_LAYOUT_RDRAM_REGISTERS_BROADCAST
      (rw)
      : ORIGIN = TUX64_PLATFORM_MIPS_N64_MEMORY_MAP_ADDRESS_RDRAM_REGISTERS_BROADCAST,
      LENGTH = 0x00080000
   TUX64_PLATFORM_MIPS_N64_MEMORY_MAP_LAYOUT_RSP_DMEM
      (rwx)
      : ORIGIN = TUX64_PLATFORM_MIPS_N64_MEMORY_MAP_ADDRESS_RSP_DMEM,
      LENGTH = 0x00001000
   TUX64_PLATFORM_MIPS_N64_MEMORY_MAP_LAYOUT_RSP_IMEM
      (rwx)
      : ORIGIN = TUX64_PLATFORM_MIPS_N64_MEMORY_MAP_ADDRESS_RSP_IMEM,
      LENGTH = 0x00001000
   TUX64_PLATFORM_MIPS_N64_MEMORY_MAP_LAYOUT_RSP_REGISTERS
      (rw)
      : ORIGIN = TUX64_PLATFORM_MIPS_N64_MEMORY_MAP_ADDRESS_RSP_REGISTERS,
      LENGTH = 0x00080000
   TUX64_PLATFORM_MIPS_N64_MEMORY_MAP_LAYOUT_RDP_REGISTERS
      (rw)
      : ORIGIN = TUX64_PLATFORM_MIPS_N64_MEMORY_MAP_ADDRESS_RDP_REGISTERS,
      LENGTH = 0x00100000
   TUX64_PLATFORM_MIPS_N64_MEMORY_MAP_LAYOUT_MI
      (rw)
      : ORIGIN = TUX64_PLATFORM_MIPS_N64_MEMORY_MAP_ADDRESS_MI,
      LENGTH = 0x00100000
   TUX64_PLATFORM_MIPS_N64_MEMORY_MAP_LAYOUT_VI
      (rw)
      : ORIGIN = TUX64_PLATFORM_MIPS_N64_MEMORY_MAP_ADDRESS_VI,
      LENGTH = 0x00100000
   TUX64_PLATFORM_MIPS_N64_MEMORY_MAP_LAYOUT_AI
      (rw)
      : ORIGIN = TUX64_PLATFORM_MIPS_N64_MEMORY_MAP_ADDRESS_AI,
      LENGTH = 0x00100000
   TUX64_PLATFORM_MIPS_N64_MEMORY_MAP_LAYOUT_PI
      (rw)
      : ORIGIN = TUX64_PLATFORM_MIPS_N64_MEMORY_MAP_ADDRESS_PI,
      LENGTH = 0x00100000
   TUX64_PLATFORM_MIPS_N64_MEMORY_MAP_LAYOUT_RI
      (rw)
      : ORIGIN = TUX64_PLATFORM_MIPS_N64_MEMORY_MAP_ADDRESS_RI,
      LENGTH = 0x00100000
   TUX64_PLATFORM_MIPS_N64_MEMORY_MAP_LAYOUT_SI
      (rw)
      : ORIGIN = TUX64_PLATFORM_MIPS_N64_MEMORY_MAP_ADDRESS_SI,
      LENGTH = 0x00100000
   TUX64_PLATFORM_MIPS_N64_MEMORY_MAP_LAYOUT_64DD_REGISTERS
      (rw)
      : ORIGIN = TUX64_PLATFORM_MIPS_N64_MEMORY_MAP_ADDRESS_64DD_REGISTERS,
      LENGTH = 0x01000000
   TUX64_PLATFORM_MIPS_N64_MEMORY_MAP_LAYOUT_64DD_IPL_ROM
      (r)
      : ORIGIN = TUX64_PLATFORM_MIPS_N64_MEMORY_MAP_ADDRESS_64DD_IPL_ROM,
      LENGTH = 0x02000000
   TUX64_PLATFORM_MIPS_N64_MEMORY_MAP_LAYOUT_CARTRIDGE_RAM
      (rw)
      : ORIGIN = TUX64_PLATFORM_MIPS_N64_MEMORY_MAP_ADDRESS_CARTRIDGE_RAM,
      LENGTH = 0x09000000
   TUX64_PLATFORM_MIPS_N64_MEMORY_MAP_LAYOUT_CARTRIDGE_ROM
      (r)
      : ORIGIN = TUX64_PLATFORM_MIPS_N64_MEMORY_MAP_ADDRESS_CARTRIDGE_ROM,
      LENGTH = 0x0fc00000
   TUX64_PLATFORM_MIPS_N64_MEMORY_MAP_LAYOUT_PIF_ROM
      (r)
      : ORIGIN = TUX64_PLATFORM_MIPS_N64_MEMORY_MAP_ADDRESS_PIF_ROM,
      LENGTH = 0x000007c0
   TUX64_PLATFORM_MIPS_N64_MEMORY_MAP_LAYOUT_PIF_RAM
      (rw)
      : ORIGIN = TUX64_PLATFORM_MIPS_N64_MEMORY_MAP_ADDRESS_PIF_RAM,
      LENGTH = 0x00000040
}

/*----------------------------------------------------------------------------*/
#endif /* _TUX64_PLATFORM_MIPS_N64_MEMORY_MAP_LD_H */

