/*----------------------------------------------------------------------------*/
/*                          Copyright (C) Tux64 2025                          */
/*                    https://github.com/bradleycha/tux64                     */
/*----------------------------------------------------------------------------*/
/* lib/src/platform/mips/n64/n64.ld - Linker script to provide definitions    */
/*    for the Nintendo 64, intended to be used in a bare-metal environment.   */
/*----------------------------------------------------------------------------*/

INCLUDE tux64/ldscripts/platform/mips/n64/memory-map.ld
INCLUDE tux64/ldscripts/platform/mips/n64/mmio.ld

