/*----------------------------------------------------------------------------*/
/*                       Copyright (C) Tux64 2025, 2026                       */
/*                    https://github.com/bradleycha/tux64                     */
/*----------------------------------------------------------------------------*/
/* rescompiler/textcompiler/src/tux64-textcompiler/formatter.c -              */
/*    Implementations for writing a parsed text file as formatted C source    */
/*    code.                                                                   */
/*----------------------------------------------------------------------------*/

#include "tux64-textcompiler/tux64-textcompiler.h"
#include "tux64-textcompiler/formatter.h"

#include <tux64/memory.h>

#include <stdlib.h>

#define TUX64_TEXTCOMPILER_FORMATTER_PRELUDE \
   "/* C source code generated by " TUX64_TEXTCOMPILER_PACKAGE_NAME " version " TUX64_TEXTCOMPILER_PACKAGE_VERSION " */\n"
#define TUX64_TEXTCOMPILER_FORMATTER_DEFINE_PREFIX \
   "#define "
#define TUX64_TEXTCOMPILER_FORMATTER_DEFINE_SUFFIX \
   " \\\n"
#define TUX64_TEXTCOMPILER_FORMATTER_BYTE_PREFIX \
   "   TUX64_LITERAL_UINT8(0x"
#define TUX64_TEXTCOMPILER_FORMATTER_BYTE_SUFFIX_NEWLINE \
   "u), \\\n"
#define TUX64_TEXTCOMPILER_FORMATTER_BYTE_SUFFIX_FINAL \
   "u)\n"
#define TUX64_TEXTCOMPILER_FORMATTER_INTEGER_PREFIX \
   "   0x"
#define TUX64_TEXTCOMPILER_FORMATTER_INTEGER_SUFFIX \
   "u\n"

#define TUX64_TEXTCOMPILER_FORMATTER_PRELUDE_CHARACTERS \
   TUX64_STRING_CHARACTERS(TUX64_TEXTCOMPILER_FORMATTER_PRELUDE)
#define TUX64_TEXTCOMPILER_FORMATTER_DEFINE_PREFIX_CHARACTERS \
   TUX64_STRING_CHARACTERS(TUX64_TEXTCOMPILER_FORMATTER_DEFINE_PREFIX)
#define TUX64_TEXTCOMPILER_FORMATTER_DEFINE_SUFFIX_CHARACTERS \
   TUX64_STRING_CHARACTERS(TUX64_TEXTCOMPILER_FORMATTER_DEFINE_SUFFIX)
#define TUX64_TEXTCOMPILER_FORMATTER_BYTE_PREFIX_CHARACTERS \
   TUX64_STRING_CHARACTERS(TUX64_TEXTCOMPILER_FORMATTER_BYTE_PREFIX)
#define TUX64_TEXTCOMPILER_FORMATTER_BYTE_SUFFIX_NEWLINE_CHARACTERS \
   TUX64_STRING_CHARACTERS(TUX64_TEXTCOMPILER_FORMATTER_BYTE_SUFFIX_NEWLINE)
#define TUX64_TEXTCOMPILER_FORMATTER_BYTE_SUFFIX_FINAL_CHARACTERS \
   TUX64_STRING_CHARACTERS(TUX64_TEXTCOMPILER_FORMATTER_BYTE_SUFFIX_FINAL)
#define TUX64_TEXTCOMPILER_FORMATTER_INTEGER_PREFIX_CHARACTERS \
   TUX64_STRING_CHARACTERS(TUX64_TEXTCOMPILER_FORMATTER_INTEGER_PREFIX)
#define TUX64_TEXTCOMPILER_FORMATTER_INTEGER_SUFFIX_CHARACTERS \
   TUX64_STRING_CHARACTERS(TUX64_TEXTCOMPILER_FORMATTER_INTEGER_SUFFIX)

#define TUX64_TEXTCOMPILER_FORMATTER_INTEGER_DIGITS_COUNT \
   2u /* formatted as 2 hexits for a single byte */

#define TUX64_TEXTCOMPILER_FORMATTER_CHARACTERS_PER_BYTE_NEWLINE \
   ( \
      TUX64_TEXTCOMPILER_FORMATTER_BYTE_PREFIX_CHARACTERS + \
      TUX64_TEXTCOMPILER_FORMATTER_INTEGER_DIGITS_COUNT + \
      TUX64_TEXTCOMPILER_FORMATTER_BYTE_SUFFIX_NEWLINE_CHARACTERS \
   )
#define TUX64_TEXTCOMPILER_FORMATTER_CHARACTERS_PER_BYTE_FINAL \
   ( \
      TUX64_TEXTCOMPILER_FORMATTER_BYTE_PREFIX_CHARACTERS + \
      TUX64_TEXTCOMPILER_FORMATTER_INTEGER_DIGITS_COUNT + \
      TUX64_TEXTCOMPILER_FORMATTER_BYTE_SUFFIX_FINAL_CHARACTERS \
   )

static Tux64UInt32
tux64_textcompiler_formatter_calculate_output_length_preprocessor_define(
   const struct Tux64String * identifier
) {
   Tux64UInt32 retn;

   retn = TUX64_LITERAL_UINT32(0u);

   retn += TUX64_LITERAL_UINT32(TUX64_TEXTCOMPILER_FORMATTER_DEFINE_PREFIX_CHARACTERS);
   retn += identifier->characters;
   retn += TUX64_LITERAL_UINT32(TUX64_TEXTCOMPILER_FORMATTER_DEFINE_SUFFIX_CHARACTERS);

   return retn;
}

static Tux64UInt32
tux64_textcompiler_formatter_calculate_output_length_item_string_data(
   const struct Tux64String * identifier,
   Tux64UInt8 characters
) {
   Tux64UInt32 retn;
   Tux64UInt8 bytes;

   retn = TUX64_LITERAL_UINT32(0u);

   bytes = (characters * TUX64_LITERAL_UINT8(sizeof(char)));

   retn += tux64_textcompiler_formatter_calculate_output_length_preprocessor_define(identifier);
   retn += (Tux64UInt32)(bytes - TUX64_LITERAL_UINT8(1u)) * TUX64_LITERAL_UINT32(TUX64_TEXTCOMPILER_FORMATTER_CHARACTERS_PER_BYTE_NEWLINE);
   retn += TUX64_LITERAL_UINT32(TUX64_TEXTCOMPILER_FORMATTER_CHARACTERS_PER_BYTE_FINAL);

   return retn;
}

static Tux64UInt32
tux64_textcompiler_formatter_calculate_output_length_item_integer(
   const struct Tux64String * identifier
) {
   Tux64UInt32 retn;

   retn = TUX64_LITERAL_UINT32(0u);

   retn += tux64_textcompiler_formatter_calculate_output_length_preprocessor_define(identifier);
   retn += TUX64_LITERAL_UINT32(TUX64_TEXTCOMPILER_FORMATTER_INTEGER_PREFIX_CHARACTERS);
   retn += TUX64_LITERAL_UINT32(TUX64_TEXTCOMPILER_FORMATTER_INTEGER_DIGITS_COUNT);
   retn += TUX64_LITERAL_UINT32(TUX64_TEXTCOMPILER_FORMATTER_INTEGER_SUFFIX_CHARACTERS);

   return retn;
}

static Tux64UInt32
tux64_textcompiler_formatter_calculate_output_length_string(
   const struct Tux64TextCompilerLexerString * string
) {
   Tux64UInt32 retn;

   retn = TUX64_LITERAL_UINT32(0u);

   retn += tux64_textcompiler_formatter_calculate_output_length_item_string_data(
      &string->identifiers.data,
      string->text.characters
   );
   retn += tux64_textcompiler_formatter_calculate_output_length_item_integer(
      &string->identifiers.length
   );

   return retn;
}

static Tux64UInt32
tux64_textcompiler_formatter_calculate_output_length(
   const struct Tux64TextCompilerLexerStringArray * string_array
) {
   Tux64UInt32 retn;
   Tux64UInt32 i;
   const struct Tux64TextCompilerLexerString * iter_string_array;

   retn = TUX64_LITERAL_UINT32(0u);

   retn += TUX64_LITERAL_UINT32(TUX64_TEXTCOMPILER_FORMATTER_PRELUDE_CHARACTERS);

   i = string_array->length;
   iter_string_array = string_array->ptr;
   do {
      retn += tux64_textcompiler_formatter_calculate_output_length_string(iter_string_array);

      iter_string_array++;
      i--;
   } while (i != TUX64_LITERAL_UINT32(0u));

   return retn;
}

static Tux64UInt8
tux64_textcompiler_formatter_string_character_convert(
   char character
) {
   if (character >= 'A' && character <= 'Z') {
      return (Tux64UInt8)(character - 'A') + TUX64_LITERAL_UINT8(0u);
   }
   if (character >= 'a' && character <= 'z') {
      return (Tux64UInt8)(character - 'a') + TUX64_LITERAL_UINT8(26u);
   }
   if (character >= '0' && character <= '9') {
      return (Tux64UInt8)(character - '0') + TUX64_LITERAL_UINT8(52u);
   }
   if (character == '%') {
      return TUX64_LITERAL_UINT8(62u);
   }
   if (character == '.') {
      return TUX64_LITERAL_UINT8(63u);
   }
   if (character == ' ') {
      return TUX64_LITERAL_UINT8(64u);
   }

   /* this should have already been filtered in the lexer */
   TUX64_UNREACHABLE;
}

static Tux64UInt8
tux64_textcompiler_formatter_encode_nibble(
   Tux64UInt8 nibble
) {
   if (nibble >= TUX64_LITERAL_UINT8(0x0au)) {
      return ('a' + nibble - TUX64_LITERAL_UINT8(0x0au));
   }

   return ('0' + nibble);
}

static Tux64UInt8 *
tux64_textcompiler_formatter_generate_allocated_byte(
   Tux64UInt8 * output_data,
   Tux64UInt8 byte
) {
   Tux64UInt8 * iter_output_data;

   iter_output_data = output_data;

   *iter_output_data++ = tux64_textcompiler_formatter_encode_nibble(byte >> TUX64_LITERAL_UINT8(4u));
   *iter_output_data++ = tux64_textcompiler_formatter_encode_nibble(byte & TUX64_LITERAL_UINT8(0x0fu));

   return iter_output_data;
}

static Tux64UInt8 *
tux64_textcompiler_formatter_generate_allocated_preprocessor_define(
   Tux64UInt8 * output_data,
   const struct Tux64String * identifier
) {
   Tux64UInt8 * iter_output_data;

   iter_output_data = output_data;

   tux64_memory_copy(
      iter_output_data,
      TUX64_TEXTCOMPILER_FORMATTER_DEFINE_PREFIX,
      TUX64_LITERAL_UINT32(TUX64_TEXTCOMPILER_FORMATTER_DEFINE_PREFIX_CHARACTERS * sizeof(char))
   );
   iter_output_data += (TUX64_TEXTCOMPILER_FORMATTER_DEFINE_PREFIX_CHARACTERS * sizeof(char));

   tux64_memory_copy(
      iter_output_data,
      identifier->ptr,
      identifier->characters * TUX64_LITERAL_UINT32(sizeof(char))
   );
   iter_output_data += (identifier->characters * TUX64_LITERAL_UINT32(sizeof(char)));

   tux64_memory_copy(
      iter_output_data,
      TUX64_TEXTCOMPILER_FORMATTER_DEFINE_SUFFIX,
      TUX64_LITERAL_UINT32(TUX64_TEXTCOMPILER_FORMATTER_DEFINE_SUFFIX_CHARACTERS * sizeof(char))
   );
   iter_output_data += (TUX64_TEXTCOMPILER_FORMATTER_DEFINE_SUFFIX_CHARACTERS * sizeof(char));

   return iter_output_data;
}

static Tux64UInt8 *
tux64_textcompiler_formatter_generate_allocated_string_character(
   Tux64UInt8 * output_data,
   char character,
   const char * identifier_suffix_ptr,
   Tux64UInt32 identifier_suffix_characters
) {
   Tux64UInt8 * iter_output_data;
   Tux64UInt8 byte;

   iter_output_data = output_data;

   byte = tux64_textcompiler_formatter_string_character_convert(character);

   tux64_memory_copy(
      iter_output_data,
      TUX64_TEXTCOMPILER_FORMATTER_BYTE_PREFIX,
      TUX64_LITERAL_UINT32(TUX64_TEXTCOMPILER_FORMATTER_BYTE_PREFIX_CHARACTERS * sizeof(char))
   );
   iter_output_data += (TUX64_TEXTCOMPILER_FORMATTER_BYTE_PREFIX_CHARACTERS * sizeof(char));

   iter_output_data = tux64_textcompiler_formatter_generate_allocated_byte(
      iter_output_data,
      byte
   );

   tux64_memory_copy(
      iter_output_data,
      identifier_suffix_ptr,
      identifier_suffix_characters * TUX64_LITERAL_UINT32(sizeof(char))
   );
   iter_output_data += (identifier_suffix_characters * sizeof(char));

   return iter_output_data;
}

static Tux64UInt8 *
tux64_textcompiler_formatter_generate_allocated_string_data(
   Tux64UInt8 * output_data,
   const struct Tux64String * identifier,
   const struct Tux64TextCompilerLexerText * text
) {
   Tux64UInt8 * iter_output_data;
   Tux64UInt8 i;
   const char * iter_text;

   iter_output_data = output_data;
   iter_output_data = tux64_textcompiler_formatter_generate_allocated_preprocessor_define(
      iter_output_data,
      identifier
   );

   i = (text->characters - TUX64_LITERAL_UINT8(1u));
   iter_text = text->ptr;
   while (i != TUX64_LITERAL_UINT8(0u)) {
      iter_output_data = tux64_textcompiler_formatter_generate_allocated_string_character(
         iter_output_data,
         *iter_text,
         TUX64_TEXTCOMPILER_FORMATTER_BYTE_SUFFIX_NEWLINE,
         TUX64_LITERAL_UINT32(TUX64_TEXTCOMPILER_FORMATTER_BYTE_SUFFIX_NEWLINE_CHARACTERS)
      );

      i--;
      iter_text++;
   }

   iter_output_data = tux64_textcompiler_formatter_generate_allocated_string_character(
      iter_output_data,
      *iter_text,
      TUX64_TEXTCOMPILER_FORMATTER_BYTE_SUFFIX_FINAL,
      TUX64_LITERAL_UINT32(TUX64_TEXTCOMPILER_FORMATTER_BYTE_SUFFIX_FINAL_CHARACTERS)
   );

   return iter_output_data;
}

static Tux64UInt8 *
tux64_textcompiler_formatter_generate_allocated_integer(
   Tux64UInt8 * output_data,
   const struct Tux64String * identifier,
   Tux64UInt8 characters
) {
   Tux64UInt8 * iter_output_data;

   iter_output_data = output_data;
   iter_output_data = tux64_textcompiler_formatter_generate_allocated_preprocessor_define(
      iter_output_data,
      identifier
   );

   tux64_memory_copy(
      iter_output_data,
      TUX64_TEXTCOMPILER_FORMATTER_INTEGER_PREFIX,
      TUX64_LITERAL_UINT32(TUX64_TEXTCOMPILER_FORMATTER_INTEGER_PREFIX_CHARACTERS * sizeof(char))
   );
   iter_output_data += (TUX64_TEXTCOMPILER_FORMATTER_INTEGER_PREFIX_CHARACTERS * sizeof(char));

   iter_output_data = tux64_textcompiler_formatter_generate_allocated_byte(
      iter_output_data,
      characters
   );

   tux64_memory_copy(
      iter_output_data,
      TUX64_TEXTCOMPILER_FORMATTER_INTEGER_SUFFIX,
      TUX64_LITERAL_UINT32(TUX64_TEXTCOMPILER_FORMATTER_INTEGER_SUFFIX_CHARACTERS * sizeof(char))
   );
   iter_output_data += (TUX64_TEXTCOMPILER_FORMATTER_INTEGER_SUFFIX_CHARACTERS * sizeof(char));

   return iter_output_data;
}

static Tux64UInt8 *
tux64_textcompiler_formatter_generate_allocated_string(
   Tux64UInt8 * output_data,
   const struct Tux64TextCompilerLexerString * string
) {
   Tux64UInt8 * iter_output_data;

   iter_output_data = output_data;

   iter_output_data = tux64_textcompiler_formatter_generate_allocated_string_data(
      iter_output_data,
      &string->identifiers.data,
      &string->text
   );
   iter_output_data = tux64_textcompiler_formatter_generate_allocated_integer(
      iter_output_data,
      &string->identifiers.length,
      (Tux64UInt8)string->text.characters
   );

   return iter_output_data;
}

static void
tux64_textcompiler_formatter_generate_allocated(
   const struct Tux64TextCompilerLexerStringArray * string_array,
   Tux64UInt8 * output_data
) {
   Tux64UInt8 * iter_output_data;
   Tux64UInt32 i;
   const struct Tux64TextCompilerLexerString * iter_string_array;

   iter_output_data = output_data;

   tux64_memory_copy(
      iter_output_data,
      TUX64_TEXTCOMPILER_FORMATTER_PRELUDE,
      TUX64_LITERAL_UINT32(TUX64_TEXTCOMPILER_FORMATTER_PRELUDE_CHARACTERS * sizeof(char))
   );
   iter_output_data += (TUX64_TEXTCOMPILER_FORMATTER_PRELUDE_CHARACTERS * sizeof(char));

   i = string_array->length;
   iter_string_array = string_array->ptr;
   do {
      iter_output_data = tux64_textcompiler_formatter_generate_allocated_string(
         iter_output_data,
         iter_string_array
      );

      i--;
      iter_string_array++;
   } while (i != TUX64_LITERAL_UINT32(0u));

   return;
}

struct Tux64TextCompilerFormatterGenerateResult
tux64_textcompiler_formatter_generate(
   const struct Tux64TextCompilerLexerStringArray * string_array
) {
   struct Tux64TextCompilerFormatterGenerateResult result;
   Tux64UInt32 output_bytes;
   Tux64UInt8 * output_data;

   output_bytes = tux64_textcompiler_formatter_calculate_output_length(string_array) * TUX64_LITERAL_UINT32(sizeof(char));

   output_data = (Tux64UInt8 *)malloc(output_bytes);
   if (output_data == NULL) {
      result.status = TUX64_TEXTCOMPILER_FORMATTER_GENERATE_STATUS_OUT_OF_MEMORY;
      return result;
   }

   tux64_textcompiler_formatter_generate_allocated(
      string_array,
      output_data
   );

   result.status = TUX64_TEXTCOMPILER_FORMATTER_GENERATE_STATUS_OK;
   result.payload.ok.data = output_data;
   result.payload.ok.bytes = output_bytes;
   return result;
}

